### ISSUE TITLE
False positive RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE and NP_LOAD_OF_KNOWN_NULL_VALUE when using empty try-with-resources

### ISSUE THREAD

**Issue by nickantzoulis** [spotbugs/spotbugs#647] opened 2018-06-01 16:09 UTC
public void falsePositive(Path myPath) throws IOException {
        try (InputStream inStream = java.nio.file.Files.newInputStream(myPath)) {
           // commented out code
        }
    }

The preceding code produces 2 false positives: 
-RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE
-NP_LOAD_OF_KNOWN_NULL_VALUE

Using jdk 1.8.0_172, spotbugs version 3.1.3

**Comment by KengoTODA** [comment] 2018-11-19 09:48
Duplicate of #259

**Comment by nmatt** [comment] 2019-05-08 00:39
I have this same problem with SpotBugs 3.1.12.
@KengoTODA: What info do you need?

**Comment by KengoTODA** [comment] 2019-05-09 08:13
@nmatt better to have a test case that reproduce this issue. Check [our contribution guide](https://github.com/spotbugs/spotbugs/blob/master/.github/CONTRIBUTING.md#before-reporting-a-problem-with-detectors) for detail.

**Comment by KengoTODA** [comment] 2020-09-25 07:41
#259 has been closed by [v4.1.3](https://github.com/spotbugs/spotbugs/releases/tag/4.1.3), please have a try.

**Closed by KengoTODA** 2020-09-25 07:41 UTC
Labels: need info

**Comment by dwalluck** [comment] 2020-10-06 19:00
In my project, the 4.1.3 release fixed all `RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE` issues, but I still seem to have `RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE` in `try-with-resources`.

Can you verify whether these two are false positives?

https://github.com/project-ncl/build-finder/blob/76f54434c4dd32366cdbd995d7664176f83eba31/cli/src/main/java/org/jboss/pnc/build/finder/cli/Main.java#L657

https://github.com/project-ncl/build-finder/blob/76f54434c4dd32366cdbd995d7664176f83eba31/cli/src/main/java/org/jboss/pnc/build/finder/cli/Main.java#L716

**Comment by dwalluck** [comment] 2020-10-06 19:03
`Error:  Low: Redundant nullcheck of session, which is known to be non-null in org.jboss.pnc.build.finder.cli.Main.call() [org.jboss.pnc.build.finder.cli.Main, org.jboss.pnc.build.finder.cli.Main] Redundant null check at Main.java:[line 657]Another occurrence at Main.java:[line 716] RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE`

https://github.com/project-ncl/build-finder/pull/237
