### ISSUE TITLE
java.lang.IllegalArgumentException in OpcodeStack.constantToInt

### ISSUE THREAD

**Issue by drabe8** [spotbugs/spotbugs#1139] opened 2020-05-28 15:12 UTC
Get this error when running an analysis:

```
The following errors occurred during analysis:
  Error processing2 < Z, signed_byte, true, return value from java.lang.Boolean.booleanValue()Z, r1 >iand< Z, return value from SpotBugsBug.getBoolean()Z > @ 13 in SpotBugsBug.myMethod : ()Ljava.lang.Boolean;
    java.lang.IllegalArgumentException: true
      At edu.umd.cs.findbugs.OpcodeStack.constantToInt(OpcodeStack.java:2197)
      At edu.umd.cs.findbugs.OpcodeStack.pushByIntMath(OpcodeStack.java:3315)
      At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:1873)
      At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.afterOpcode(OpcodeStackDetector.java:83)
      At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:880)
      At edu.umd.cs.findbugs.detect.FieldItemSummary.visit(FieldItemSummary.java:131)
      At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
      At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:65)
      At org.apache.bcel.classfile.Code.accept(Code.java:131)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:397)
      At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
      At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.lambda$null$1(FindBugs2.java:1108)
      At java.util.concurrent.FutureTask.run(FutureTask.java:266)
      At edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
      At java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:238)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
      At edu.umd.cs.findbugs.gui2.BugLoader.doAnalysis(BugLoader.java:101)
      At edu.umd.cs.findbugs.gui2.AnalyzingDialog$AnalysisThread.run(AnalyzingDialog.java:257)
 ```

This is the source code:
```
public class SpotBugsBug
{
	public Boolean myMethod()
	{
		Boolean numeric = true;

		numeric &= getBoolean();

		return numeric;
	}

	private boolean getBoolean()
	{
		return false;
	}
}

```

**Comment by iloveeclipse** [comment] 2020-05-28 20:35
I can confirm it. Funny enough, changing `Boolean numeric = true;` to `boolean numeric = true;` "fixes" the error.

I guess changing edu.umd.cs.findbugs.OpcodeStack.constantToInt(Item) to accept boolean (Z) should do the magic.

Something like this:
```
diff --git a/spotbugs/src/main/java/edu/umd/cs/findbugs/OpcodeStack.java b/spotbugs/src/main/java/edu/umd/cs/findbugs/OpcodeStack.java
index c33e0ca..9b25ede 100644
--- a/spotbugs/src/main/java/edu/umd/cs/findbugs/OpcodeStack.java
+++ b/spotbugs/src/main/java/edu/umd/cs/findbugs/OpcodeStack.java
@@ -2194,6 +2194,9 @@
         if (constant instanceof Character) {
             return ((Character) constant).charValue();
         }
+        if (constant instanceof Boolean) {
+            return ((Boolean) constant).booleanValue()? 1 : 0;
+        }
         throw new IllegalArgumentException(String.valueOf(constant));
     }
```

**Comment by iloveeclipse** [comment] 2020-09-29 18:53
THis is a duplicate of #893

**Closed by iloveeclipse** 2020-09-29 18:53 UTC
Labels: bug
