### ISSUE TITLE
Signature of eclipse-plugin expired

### ISSUE THREAD

**Issue by cpfeiffer** [spotbugs/spotbugs#2980] opened 2024-05-07 13:52 UTC
#2008 is already closed, so maybe comment https://github.com/spotbugs/spotbugs/issues/2008#issuecomment-1763774427 got overlooked.

The signature of the eclipse-plugin has expired (two years ago) 
@KengoTODA

**Comment by JuditKnoll** [comment] 2024-11-28 08:35
Closing this as a duplicate of https://github.com/spotbugs/spotbugs/issues/2696.

**Closed by JuditKnoll** 2024-11-28 08:35 UTC
