### ISSUE TITLE
java.lang.AssertionError: frame_type field doesn't exist at edu.umd.cs.findbugs.StackMapAnalyzer.lambda$static$0(StackMapAnalyzer.java:150)

### ISSUE THREAD

**Issue by Cathy01** [spotbugs/spotbugs#1223] opened 2020-07-18 06:40 UTC
The error was copied to the clipboard. Press Ctrl+V

**Comment by KengoTODA** [comment] 2020-07-18 08:17
Try version 4.0.6 which contains fix for this problem.

Duplicate of #1176

**Closed** 2023-07-18 01:52 UTC
