### ISSUE TITLE
Exception analyzing ... using detector edu.umd.cs.findbugs.detect.RedundantConditions

### ISSUE THREAD

**Issue by gargooza** [spotbugs/spotbugs#608] opened 2018-04-05 16:00 UTC
I'm getting a lot of the same exception:
```
 Exception analyzing com.redacted.MyTroublesomeClassToAnalyze using detector edu.umd.cs.findbugs.detect.RedundantConditions
   java.lang.IndexOutOfBoundsException: fromIndex: 1303 > toIndex: 1114
     At java.util.BitSet.checkRange(BitSet.java:366)
     At java.util.BitSet.set(BitSet.java:481)
     At edu.umd.cs.findbugs.classfile.engine.bcel.ValueRangeAnalysisFactory.analyze(ValueRangeAnalysisFactory.java:789)
     At edu.umd.cs.findbugs.classfile.engine.bcel.ValueRangeAnalysisFactory.analyze(ValueRangeAnalysisFactory.java:87)
     At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
     At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
     At edu.umd.cs.findbugs.detect.RedundantConditions.visitClassContext(RedundantConditions.java:67)
     At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1079)
     At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:280)
     At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
     At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1187)
```

MyTroublesomeClassToAnalyze is not the only class for which this is a problem. Other classes throw the same exception, just with different indices for the IndexOutOfBoundsException:
```
MyTroublesomeClassToAnalyze.java: java.lang.IndexOutOfBoundsException: fromIndex: 1303 > toIndex: 1114
AnotherClass.java: java.lang.IndexOutOfBoundsException: fromIndex: 1078 > toIndex: 919
YetAnother.java: java.lang.IndexOutOfBoundsException: fromIndex: 1226 > toIndex: 1050
EnoughIsEnough.java: java.lang.IndexOutOfBoundsException: fromIndex: 969 > toIndex: 808
```

Each of these classes extends a common base class, so they do have that in common.

**Comment by victorwss** [comment] 2018-04-08 06:08
Can you post the code of those classes?

**Comment by gargooza** [comment] 2018-04-09 12:09
Sorry, but I cannot post the code as it's proprietary

**Comment by iloveeclipse** [comment] 2018-04-09 12:55
@gargooza : but you can try to isolate a snippet which shows the problem or you can close this issue as "can't reproduce".

**Comment by gargooza** [comment] 2018-04-09 17:55
I was able to isolate the issue. I cannot actually paste code, but the problem line in each of the exceptions is an assert. If I comment out the assert, SpotBugs succeeds. The assert is nested within some loop/conditional blocks like this:
```
methodThatFails() {
  for() {
    while() {
      if() {
        if() {
        }
        else {
          assert( someCondition ) : "assertion failure message";
        }
      }
    }
  }
}
```

**Comment by ThrawnCA** [comment] 2018-10-29 00:10
Are you able to provide the (bytecode) output of `javap -v`? It looks like this code depends on your other classes, so would be difficult for someone else to compile.

**Comment by abcfy2** [comment] 2019-05-09 10:43
I can reproduce this issue. Here is my project: https://github.com/DTeam-Top/grails-rest-seed

```bash
git clone --depth 1 https://github.com/DTeam-Top/grails-rest-seed.git
./gradlew spotbugsMain
```

Will see this error:

```
The following errors occurred during analysis:
  Exception analyzing top.dteam.earth.backend.user.UserController using detector edu.umd.cs.findbugs.detect.FindNullDeref
    java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
      At java.util.BitSet.set(BitSet.java:444)
      At edu.umd.cs.findbugs.ba.ClassContext.linesMentionedMultipleTimes(ClassContext.java:819)
      At edu.umd.cs.findbugs.ba.npe.NullDerefAndRedundantComparisonFinder.<init>(NullDerefAndRedundantComparisonFinder.java:135)
      At edu.umd.cs.findbugs.detect.FindNullDeref.analyzeMethod(FindNullDeref.java:277)
      At edu.umd.cs.findbugs.detect.FindNullDeref.visitClassContext(FindNullDeref.java:209)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing top.dteam.earth.backend.user.UserController using detector edu.umd.cs.findbugs.detect.LoadOfKnownNullValue
    java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
      At java.util.BitSet.set(BitSet.java:444)
      At edu.umd.cs.findbugs.ba.ClassContext.linesMentionedMultipleTimes(ClassContext.java:819)
      At edu.umd.cs.findbugs.detect.LoadOfKnownNullValue.analyzeMethod(LoadOfKnownNullValue.java:79)
      At edu.umd.cs.findbugs.detect.LoadOfKnownNullValue.visitClassContext(LoadOfKnownNullValue.java:62)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing top.dteam.earth.backend.user.UserController using detector edu.umd.cs.findbugs.detect.FindDeadLocalStores
    java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
      At java.util.BitSet.set(BitSet.java:444)
      At edu.umd.cs.findbugs.ba.ClassContext.linesMentionedMultipleTimes(ClassContext.java:819)
      At edu.umd.cs.findbugs.detect.FindDeadLocalStores.analyzeMethod(FindDeadLocalStores.java:213)
      At edu.umd.cs.findbugs.detect.FindDeadLocalStores.visitClassContext(FindDeadLocalStores.java:194)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing top.dteam.earth.backend.user.UserController using detector edu.umd.cs.findbugs.detect.FindBadCast2
    java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
      At java.util.BitSet.set(BitSet.java:444)
      At edu.umd.cs.findbugs.ba.ClassContext.linesMentionedMultipleTimes(ClassContext.java:819)
      At edu.umd.cs.findbugs.detect.FindBadCast2.analyzeMethod(FindBadCast2.java:198)
      At edu.umd.cs.findbugs.detect.FindBadCast2.visitClassContext(FindBadCast2.java:111)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing top.dteam.earth.backend.user.ManagementController using detector edu.umd.cs.findbugs.detect.FindNullDeref
    java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
      At java.util.BitSet.set(BitSet.java:444)
      At edu.umd.cs.findbugs.ba.ClassContext.linesMentionedMultipleTimes(ClassContext.java:819)
      At edu.umd.cs.findbugs.ba.npe.NullDerefAndRedundantComparisonFinder.<init>(NullDerefAndRedundantComparisonFinder.java:135)
      At edu.umd.cs.findbugs.detect.FindNullDeref.analyzeMethod(FindNullDeref.java:277)
      At edu.umd.cs.findbugs.detect.FindNullDeref.visitClassContext(FindNullDeref.java:209)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing top.dteam.earth.backend.user.ManagementController using detector edu.umd.cs.findbugs.detect.LoadOfKnownNullValue
    java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
      At java.util.BitSet.set(BitSet.java:444)
      At edu.umd.cs.findbugs.ba.ClassContext.linesMentionedMultipleTimes(ClassContext.java:819)
      At edu.umd.cs.findbugs.detect.LoadOfKnownNullValue.analyzeMethod(LoadOfKnownNullValue.java:79)
      At edu.umd.cs.findbugs.detect.LoadOfKnownNullValue.visitClassContext(LoadOfKnownNullValue.java:62)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing top.dteam.earth.backend.user.ManagementController using detector edu.umd.cs.findbugs.detect.FindDeadLocalStores
    java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
      At java.util.BitSet.set(BitSet.java:444)
      At edu.umd.cs.findbugs.ba.ClassContext.linesMentionedMultipleTimes(ClassContext.java:819)
      At edu.umd.cs.findbugs.detect.FindDeadLocalStores.analyzeMethod(FindDeadLocalStores.java:213)
      At edu.umd.cs.findbugs.detect.FindDeadLocalStores.visitClassContext(FindDeadLocalStores.java:194)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing top.dteam.earth.backend.user.ManagementController using detector edu.umd.cs.findbugs.detect.FindBadCast2
    java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
      At java.util.BitSet.set(BitSet.java:444)
      At edu.umd.cs.findbugs.ba.ClassContext.linesMentionedMultipleTimes(ClassContext.java:819)
      At edu.umd.cs.findbugs.detect.FindBadCast2.analyzeMethod(FindBadCast2.java:198)
      At edu.umd.cs.findbugs.detect.FindBadCast2.visitClassContext(FindBadCast2.java:111)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
      At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
      At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
      At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      At java.lang.reflect.Method.invoke(Method.java:498)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
      At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
      At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
      At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
      At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
      At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
      At java.lang.Thread.run(Thread.java:748)
The following classes needed for analysis were missing:
  void


BUILD SUCCESSFUL in 50s
5 actionable tasks: 3 executed, 2 up-to-date
```

**Comment by archiecobbs** [comment] 2022-06-10 17:33
Still happening with Maven plugin version 4.7.0.0.

I get a bunch of exceptions that look like this:
```
     [java] The following errors occurred during analysis:
     [java]   Exception analyzing com.patientexp.pcom.sms.DefaultSMSQueueProcessor$AjcClosure19 using detector edu.umd.cs.findbugs.detect.FindPotentialSecurityCheckBasedOnUntrustedSource
     [java]     java.lang.NullPointerException
     [java]       At edu.umd.cs.findbugs.detect.FindPotentialSecurityCheckBasedOnUntrustedSource.afterOpcode(FindPotentialSecurityCheckBasedOnUntrustedSource.java:378)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:880)
     [java]       At edu.umd.cs.findbugs.detect.FindPotentialSecurityCheckBasedOnUntrustedSource.visit(FindPotentialSecurityCheckBasedOnUntrustedSource.java:155)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
     [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:65)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:131)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:397)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1108)
     [java]       At java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java]       At edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
     [java]       At java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:238)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
```

**Comment by gtoison** [comment] 2024-03-02 18:06
@archiecobbs I think your issue was a duplicate of #2041 and was fixed in 4.7.1 by #2054

**Comment by archiecobbs** [comment] 2024-03-03 14:21
@gtoison thanks for the pointer.

**Comment by JuditKnoll** [comment] 2024-03-04 08:41
The issue is recreated and fixed in https://github.com/spotbugs/spotbugs/pull/2887.

**Closed by JuditKnoll** 2024-03-04 08:41 UTC
Labels: need info
