### ISSUE TITLE
Issue during analysis of SpringCGLIB after Spring Boot Native build

### ISSUE THREAD

**Issue by klopfdreh** [spotbugs/spotbugs#3059] opened 2024-07-31 05:44 UTC
We are currently testing Spring Boot Native builds and found out that during the analysis SpotBugs failed.

See the following `maven_plugin_logs.txt`

[maven_plugin_logs.txt](https://github.com/user-attachments/files/16436767/maven_plugin_logs.txt)

Initial lines of error:
```plain
[java]   Error analyzing mypackage.steps.prepare.StepS3FilesPrepareExecutionListener$$SpringCGLIB$$0.setCallbacks([Lorg/springframework/cglib/proxy/Callback;)V for unconditional deref training
[java]     edu.umd.cs.findbugs.ba.CFGBuilderException: Invalid stack at    2: dup2[92](1) when checking    8: putfield[181](3) 58
```

See a minimal example here: https://github.com/klopfdreh/native-cloud-config-test and add spotbugs maven plugin together with a configuration that creates a SpringCGLIB 

`suppression.xml` file:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<FindBugsFilter xmlns="https://github.com/spotbugs/filter/3.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://github.com/spotbugs/filter/3.0.0 https://raw.githubusercontent.com/spotbugs/spotbugs/3.1.0/spotbugs/etc/findbugsfilter.xsd">
    <!-- Ignore checking for Spring Boot AOT generated classes -->
    <Match>
        <Or>
            <Class name="~.*\$\$SpringCGLIB\$\$.*"/>
        </Or>
    </Match>
    <Match>
        <Or>
            <Class name="~.*__BeanDefinitions.*"/>
        </Or>
    </Match>
    <Match>
        <Or>
            <Class name="~.*__BeanFactoryRegistrations.*"/>
        </Or>
    </Match>
    <Match>
        <Or>
            <Class name="~.*RetryTemplateFactory.*"/>
        </Or>
    </Match>
    <Match>
        <Or>
            <Class name="~.*DefaultDataSourceConfiguration.*"/>
        </Or>
    </Match>
</FindBugsFilter>
```

Plugin Configuration
```xml
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>4.8.5.0</version>
                    <executions>
                        <execution>
                            <id>spotbugs</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>verify</goal>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <xmlOutput>true</xmlOutput>
                        <excludeFilterFile>/mypath/suppression.xml</excludeFilterFile>
                        <effort>Max</effort>
                        <fork>false</fork>
                        <jvmArgs>-Djava.security.manager=allow</jvmArgs>
                        <plugins>
                            <plugin>
                                <groupId>com.mebigfatguy.sb-contrib</groupId>
                                <artifactId>sb-contrib</artifactId>
                                <version>7.6.4</version>
                            </plugin>
                            <plugin>
                                <groupId>com.h3xstream.findsecbugs</groupId>
                                <artifactId>findsecbugs-plugin</artifactId>
                                <version>1.13.0</version>
                            </plugin>
                        </plugins>
                    </configuration>
                </plugin>
```

**Comment by gtoison** [comment] 2024-08-01 06:24
Thank you for reporting the issue; according to the logs SpotBugs fails when trying to build the CFG of this method: `analyzing mypackage.steps.prepare.StepS3FilesPrepareExecutionListener$$SpringCGLIB$$0.setCallbacks([Lorg/springframework/cglib/proxy/Callback;)V`

Could you please provide the corresponding `.class` files? Or even a zip with the built project so we have all the .class files? I do not have docker installed and (if I understand correctly) it is required to build a Spring native project

**Comment by klopfdreh** [comment] 2024-08-01 10:25
Sadly I can't provide the classes as they belong to a private code base. The class however is only one which `extends org.springframework.batch.core.listener.StepExecutionListenerSupport` so nothing special here.

docker is not required - you just need to download any GraalVM with native-image support - see: https://docs.spring.io/spring-boot/reference/packaging/native-image/advanced-topics.html#packaging.native-image.advanced.converting-executable-jars.native-image Liberica NIK supports all platforms - mac / windows / linux.

As I mention earlier - those are classes generated from the AOT compiler of Spring Boot. You should be able to reproduce this easily by creating a Spring Boot Starter Application and add some `@Component` classes.

**Comment by gtoison** [comment] 2024-08-01 12:15
I tried reproducing the problem with the https://github.com/klopfdreh/native-cloud-config-test project but can't seem to get the AOT to work, I'm doing `mvn verify -Pnative -Dmaven.test.skip=true` but the `process-aot` seems to try connecting to a localhost web server, I'm not sure why.

Can you please walk me through the steps to reproduce this? I don't know Spring Native and I have no idea what I'm doing :)

**Comment by klopfdreh** [comment] 2024-08-02 05:27
Hey @gtoison - I created a minimal setup to reproduce the issue: https://github.com/klopfdreh/spotbugs-aot-test - I didn't tell you that you don't have to compile the native-image but just do the Spring Boot AOT processing - I am sorry for that.

Steps to reproduce:
1. Checkout the repository
2. run `mvn clean verify`

Result:

I received the following error message: [log.txt](https://github.com/user-attachments/files/16465801/log.txt)

**Comment by gtoison** [comment] 2024-08-02 07:00
Thank you very much for the reproducer, this helps immensely!
The problematic bytecode is:
```
// Method descriptor #303 ([Lorg/springframework/cglib/proxy/Callback;)V
  // Stack: 5, Locals: 2
  public void setCallbacks(org.springframework.cglib.proxy.Callback[] arg0);
     0  aload_0 [this]
     1  aload_1 [arg0]
     2  dup2
     3  iconst_0
     4  aaload
     5  checkcast org.springframework.cglib.proxy.MethodInterceptor [63]
     8  putfield spotbugs.aot.test.SpotBugsAotComponent$$SpringCGLIB$$0.CGLIB$CALLBACK_0 : org.springframework.cglib.proxy.MethodInterceptor [51]
```

I think the issue is in the way `dup2` is handled and I see that https://github.com/spotbugs/spotbugs/issues/2145 fixed a very similar problem (with `dup_x2`).

The code was initially added to solve this issue: https://sourceforge.net/p/findbugs/bugs/1027/

At the same time you might want to run SpotBugs before the AOT processing: hopefully there aren't bugs in the bytecode produced by CGLIB and you would be more interested in potential issues in the code you have written.
There was a similar discussion recently with SpotBugs failing to analyze bytecode modified by Jacoco.

**Comment by klopfdreh** [comment] 2024-08-02 07:33
> At the same time you might want to run SpotBugs before the AOT processing: hopefully there aren't bugs in the bytecode produced by CGLIB and you would be more interested in potential issues in the code you have written.
There was a similar discussion recently with SpotBugs failing to analyze bytecode modified by Jacoco.

That’s the point - I think it is not good to run the spotbugs plugin before certain code is generated especially not if you use findsecbugs-plugin.

So my question would be to also include dub2 and refactor the code so that it can be enhanced further more if required.

**Comment by gtoison** [comment] 2024-08-02 08:46
I'm not disagreeing, in any case SpotBugs shouldn't crash when analysing valid bytecode.
I need to better understand what the code is doing but my gut feeling is that we shouldn't add yet another case for `dup2`: there are serveral "dup something" bytecode instructions, it would be better if we could find a way to handle all of them

**Comment by klopfdreh** [comment] 2024-08-02 09:20
> it would be better if we could find a way to handle all of them

Yes that would be great - I meant this with „ refactor the code so that it can be enhanced further more if required.“

Anyway thanks for your effort!

**Comment by gtoison** [comment] 2024-08-05 11:24
So this should be fixed by #3064 and should work in the upcoming version of SpotBugs

**Closed** 2024-08-05 12:12 UTC

**Comment by klopfdreh** [comment] 2024-08-12 06:50
Hey @gtoison - may I ask when do you plan the next release?

**Comment by gtoison** [comment] 2024-08-14 06:42
There was the same question in another unrelated issue and @hazendaz said that it could be in a couple of weeks, but no promises as this largely depends on finding available free time

**Comment by klopfdreh** [comment] 2025-02-17 06:40
Hey @gtoison - we tested SpotBut 4.9.1.0 (https://github.com/spotbugs/spotbugs-maven-plugin/releases/tag/spotbugs-maven-plugin-4.9.1.0) with the spotbugs-maven-plugin, released issued with https://github.com/spotbugs/spotbugs-maven-plugin/issues/996 and I happily can confirm that the fix is working like a charm. 😃

Thanks a lot for your help!

**Comment by gtoison** [comment] 2025-02-17 07:04
Thank you very much for testing! And thanks for your patience 👍
