### ISSUE TITLE
Frequent UI freezes in Eclipse when SpotBugs is installed

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#504] opened 2017-11-28 13:11 UTC
Under Eclipse Oxygen.1a, I get frequent (essentially, on any save) UI freezes when I have SpotBugs installed. `jstack` reveals the following

    "main" #1 prio=6 os_prio=31 tid=0x00007fc242002000 nid=0x130f runnable [0x00007fff5db8e000]
       java.lang.Thread.State: RUNNABLE
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
          at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
          at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
          at org.eclipse.core.internal.resources.MarkerManager.visitorFindMarkers(MarkerManager.java:620)
          at org.eclipse.core.internal.resources.MarkerManager.doFindMarkers(MarkerManager.java:283)
          at org.eclipse.core.internal.resources.MarkerManager.findMarkers(MarkerManager.java:268)
          at org.eclipse.core.internal.resources.Resource.findMarkers(Resource.java:987)
          at de.tobject.findbugs.reporter.MarkerUtil.getMarkers(MarkerUtil.java:1001)
          at de.tobject.findbugs.builder.WorkItem.getMarkers(WorkItem.java:309)
          at de.tobject.findbugs.builder.WorkItem.getMarkerCount(WorkItem.java:284)
          at de.tobject.findbugs.decorators.ResourceBugCountDecorator.decorateText(ResourceBugCountDecorator.java:54)
          at org.eclipse.ui.internal.decorators.FullDecoratorDefinition.decorateText(FullDecoratorDefinition.java:133)
          at org.eclipse.ui.internal.decorators.FullTextDecoratorRunnable.run(FullTextDecoratorRunnable.java:24)
          at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
          at org.eclipse.ui.internal.decorators.DecoratorManager.safeDecorateText(DecoratorManager.java:497)
          at org.eclipse.ui.internal.decorators.DecoratorManager.decorateText(DecoratorManager.java:453)
          at org.eclipse.ui.internal.decorators.DecoratorManager$ManagedWorkbenchLabelDecorator.decorateText(DecoratorManager.java:151)
          at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.getStyledText(DecoratingStyledCellLabelProvider.java:202)
          at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.update(DelegatingStyledCellLabelProvider.java:106)
          at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.update(DecoratingStyledCellLabelProvider.java:131)
          at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:141)
          at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:946)
          at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:117)
          at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
          at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
          at org.eclipse.ui.internal.JFaceUtil$$Lambda$8/748316439.run(Unknown Source)
          at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
          at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1025)
          at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:475)
          at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
          at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
          at org.eclipse.ui.internal.JFaceUtil$$Lambda$8/748316439.run(Unknown Source)
          at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
          at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2159)
          at org.eclipse.jface.viewers.StructuredViewer.internalUpdate(StructuredViewer.java:2142)
          at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2083)
          at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:542)
          at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2027)
          at org.eclipse.jface.viewers.StructuredViewer.handleLabelProviderChanged(StructuredViewer.java:1203)
          at org.eclipse.jdt.internal.ui.viewsupport.ProblemTreeViewer.handleLabelProviderChanged(ProblemTreeViewer.java:206)
          at org.eclipse.jface.viewers.ContentViewer$1.labelProviderChanged(ContentViewer.java:99)
          at org.eclipse.jface.viewers.BaseLabelProvider$1.run(BaseLabelProvider.java:72)
          at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
          at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
          at org.eclipse.ui.internal.JFaceUtil$$Lambda$8/748316439.run(Unknown Source)
          at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
          at org.eclipse.jface.viewers.BaseLabelProvider.fireLabelProviderChanged(BaseLabelProvider.java:69)
          at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.lambda$0(DecoratingStyledCellLabelProvider.java:75)
          at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider$$Lambda$199/28782490.labelProviderChanged(Unknown Source)
          at org.eclipse.ui.internal.decorators.DecoratorManager$1.run(DecoratorManager.java:374)
          at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
          at org.eclipse.ui.internal.decorators.DecoratorManager.fireListener(DecoratorManager.java:371)
          at org.eclipse.ui.internal.decorators.DecorationScheduler$3.runInUIThread(DecorationScheduler.java:485)
          at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
          at org.eclipse.ui.progress.UIJob$$Lambda$287/1773814305.run(Unknown Source)
          at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
          at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
          - locked <0x0000000773b00a08> (a org.eclipse.swt.widgets.RunnableLock)
          at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4033)
          at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
          at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
          at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
          at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
          at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
          at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
          at org.eclipse.ui.internal.Workbench$$Lambda$15/67570169.run(Unknown Source)
          at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
          at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
          at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
          at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
          at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
          at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
          at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
          at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
          at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
          at java.lang.reflect.Method.invoke(Method.java:498)
          at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
          at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
          at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

I am reminded a bit about [Eclipse Bug 450663](https://bugs.eclipse.org/bugs/show_bug.cgi?id=450663#c18), but I don’t group by working sets and have just 9 warnings in my workspace, so this issue may be unrelated.

Can anyone else reproduce?

**Comment by iloveeclipse** [comment] 2017-11-29 15:47
Unfortunately no. We have big workspaces, ~3000 spotbugs warnings but nothing similar (at least with 4.6.3 / RHEL 7.2 / Java 8).

**Comment by cdietrich** [comment] 2017-11-29 15:50
we see/saw the same in xtext codebase. this made us remove findbugs from developer tooling

**Comment by cdietrich** [comment] 2017-11-29 15:50
see https://github.com/spotbugs/spotbugs/issues/285

**Comment by cdietrich** [comment] 2017-11-29 15:51
@iloveeclipse do you have the count decorators enabled in your codebase?

**Comment by iloveeclipse** [comment] 2017-11-29 16:01
Sure. Why would I implement a feature which I don't use by myself?

**Comment by rubenporras** [comment] 2021-08-31 14:14
I see the same problem in my environment, which uses Xtext (I do not know if it is related). Using eclipse 2019-09 (4.13).

**Comment by iloveeclipse** [comment] 2022-02-06 08:53
Duplicate of #285

**Closed by iloveeclipse** 2022-02-06 08:53 UTC
Labels: eclipse_plugin
