### ISSUE TITLE
MC_OVERRIDABLE_METHOD_CALL_IN_READ_OBJECT false positive in 4.8.4

### ISSUE THREAD

**Issue by kohlschuetter** [spotbugs/spotbugs#2957] opened 2024-04-19 13:57 UTC
With 4.8.4 (and latest 4.8.5-SNAPSHOT), I'm getting two false-positive errors:

```
[ERROR] Medium: Overridable method equals is called from readObject. [org.newsclub.net.unix.AFSocketAddress] At AFSocketAddress.java:[line 906] MC_OVERRIDABLE_METHOD_CALL_IN_READ_OBJECT
[ERROR] Medium: Overridable method readUTF is called from readObject. [org.newsclub.net.unix.AFSocketAddress] At AFSocketAddress.java:[line 905] MC_OVERRIDABLE_METHOD_CALL_IN_READ_OBJECT
```

Method in question:

```
private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    in.defaultReadObject();

    String af = in.readUTF(); // 905 HERE
    if ("undefined".equals(af)) { // 906 HERE
      this.addressFamily = null;
    } else {
      this.addressFamily = Objects.requireNonNull(AFAddressFamily.getAddressFamily(af),
          "address family");
    }
  }
```

In 905, it's clearly a false-positive because the object has been passed as the `ObjectInputStream`.
In 906, it's clearly a false-positive because we're operating on a string constant.

I think generally, these errors should not occur because they don't work on `this` (the instance where `readObject` is called) but on some other object.

I understand MC_OVERRIDABLE_METHOD_CALL_IN_READ_OBJECT has been newly introduced in 4.8.4.

**Comment by kohlschuetter** [comment] 2024-04-19 17:12
For what it's worth, I'm using spotbugs-maven-plugin 4.8.3.1 (or 4.8.4.0) with spotbugs 4.8.5-SNAPSHOT.
I couldn't reproduce this via spotbugs-tests, so here are the steps to reproduce:

1. Clone junixsocket from https://github.com/kohlschutter/junixsocket/tree/813f25a01fe35958b2ac2282d8f7f371f1471af0
2. Clone kohlschutter-parent from https://github.com/kohlschutter/kohlschutter-parent/tree/212cf152f4ca1ece6c417c475a8c5b6254538edc
3. Make sure both projects are siblings in the same directory
4. Build/check junixsocket-common (should succeed):
```
cd junixsocket/junixsocket-common
mvn clean compile spotbugs:check
```
5. Modify kohlschutter-parent/pom.xml: uncomment the `<dependencies>` section to include a specific spotbugs version:
```
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>${spotbugs.plugin.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.github.spotbugs</groupId>
                            <artifactId>spotbugs</artifactId>
                            <version>4.8.4</version><!-- or 4.8.5-SNAPSHOT -->
                        </dependency>
                    </dependencies>
                </plugin>
```
6. Re-run check from step 4 above (which will now fail)

**Comment by dsubelman** [comment] 2024-04-20 21:49
I'm having the same issue with `readInt()`. Both methods,  `readUTF()` and `readInt()`, are not final. However, for example, `defaultReadObject()` is also not final, but it doesn't trigger any bug alert.
Am I missing something?

**Comment by gtoison** [comment] 2024-04-21 06:42
Hello @isuckatcs, maybe this changed with #2895, could you please have a look a this issue ?

**Comment by isuckatcs** [comment] 2024-04-21 13:06
> However, for example, defaultReadObject() is also not final, but it doesn't trigger any bug alert.

Here the error is not triggered, because `defaultReadObject()` is an exception that can be called.

See [SER09-J](https://wiki.sei.cmu.edu/confluence/display/java/SER09-J.+Do+not+invoke+overridable+methods+from+the+readObject%28%29+method):
```
Exceptions
SER09-J-EX0: The readObject() method may invoke the overridable methods defaultReadObject() and readFields() in class java.io.ObjectInputStream [SCG 2009].
```

AFAIK the way the check is written should prevent these errors to be reported, but after thinking about it further these might actually be correct to report. SER09-J says the following:

> Invoking overridable methods from the readObject() method can provide the overriding method with access to the object's state before it is fully initialized.

When the overridden method is invoked, the stack frame looks like this:
```
- readObject()
  - overriddenMethod()
```
This means, that if the caller of `overriddenMethod()` starts walking the stack, it can actually have access to the object by fishing for `this` in the stack frame of `readObject()`. This is something that is easily possible to do in C++, see my example on [godbolt](https://godbolt.org/z/84Erf53Th). I don't see why this wouldn't be possible in Java too using some trick.

@JuditKnoll any thought on this?

**Comment by dsubelman** [comment] 2024-04-21 20:10
Thanks for the complete explanation. You are correct that both `defaultReadObject()` and `readFields()` don't report any errors. However, with `readFields()` and the `get(String name, Object val)` method it does report an error for the `get` method:

```
ObjectInputStream.GetField fieldValues = ois.readFields();
String nameField = (String) fieldValues.get("name", "null"); // Error reported here
```

Is that the expected behavior?

**Comment by isuckatcs** [comment] 2024-04-21 22:42
@dsubelman I double checked your example, and according to the current rules of the check, the `get()` call should be reported.

```java
private boolean shouldIgnoreCallInReadObject(XMethod method) {
    // SER09-J-EX0: The readObject() method may invoke the overridable methods defaultReadObject() and readFields()
    // in class java.io.ObjectInputStream
    boolean inOIS = "java.io.ObjectInputStream".equals(method.getClassName());
    String methodName = method.getName();
    return inOIS && ("defaultReadObject".equals(methodName) || "readFields".equals(methodName));
}

if (!shouldIgnoreCallInReadObject(method) && !method.isPrivate() && !method.isFinal()) {
    bugAccumulator.accumulateBug(
            new BugInstance(this, "MC_OVERRIDABLE_METHOD_CALL_IN_READ_OBJECT", NORMAL_PRIORITY)
                    .addClass(this)
                    .addMethod(caller)
                    .addString(method.getName()), sourceLine);
    return false;
}
```
These rules correspong to the wording of [SER09-J](https://wiki.sei.cmu.edu/confluence/display/java/SER09-J.+Do+not+invoke+overridable+methods+from+the+readObject%28%29+method), according to which
> The readObject() method must not call any overridable methods. [...] The readObject() method may invoke the overridable methods defaultReadObject() and readFields() in class java.io.ObjectInputStream.

The rule says *any* overridable methods, not just the ones invoked on `this`. 

Initially I remembered that the check is written so that it only checks calls on `this`, but that limitation is only there for indirect calls (See [this discussion](https://github.com/spotbugs/spotbugs/pull/2895#discussion_r1519328003) for more details). I would only add that by the time, I was answering this, I didn't think about walking the stack from the overridden method. With that in mind, I think that limitation shouldn't be there and the call mentioned in the discussion should be reported too, assuming that the C++ example I gave can be translated to Java too.

**Comment by dsubelman** [comment] 2024-04-21 23:29
[@isuckatcs](https://github.com/isuckatcs) understood, thanks again for the complete explanation.

**Comment by kohlschuetter** [comment] 2024-04-22 06:54
> The rule says any overridable methods, not just the ones invoked on this.

I'm not quite following this logic.
The example in SER09-J clearly describes what they mean — an overridable method of the instance in question, not just any "method overridable in theory".

I mean, how else would you be able to call `in.readUTF()`? We don't control the very subclass of ObjectInputStream that gets passed to readObject, nor a we able to subclass it further.

Yes, you may have a scenario where calling some other object's method indirectly calls an overridable method of our instance, but I'm pretty sure you won't be able reliably detect these cases while allowing all others, so why bother going beyond the exact, simple scenario given in SER09-J?

Coming back to my original problem, could you please  if I'm mistaken, suggest how I should rewrite the following method so spotbugs won't fail?

```
private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    in.defaultReadObject();

    String af = in.readUTF(); // 905 HERE
    if ("undefined".equals(af)) { // 906 HERE
      this.addressFamily = null;
    } else {
      this.addressFamily = Objects.requireNonNull(AFAddressFamily.getAddressFamily(af),
          "address family");
    }
  }
```

**Comment by isuckatcs** [comment] 2024-04-22 08:39
> I'm not quite following this logic.
The example in SER09-J clearly describes what they mean — an overridable method of the instance in question, not just any "method overridable in theory".

You are correct that the example only mentions the overridable method of the instance, but in that context the exception wouldn't make sense I think.

> SER09-J-EX0: The readObject() method may invoke the overridable methods defaultReadObject() and readFields() in class java.io.ObjectInputStream

If we only care about overridable methods invoked on the instance, why does it have to be explicitly stated, that calling 2 overridable methods and only these 2 on `java.io.ObjectInputStream` is allowed? The input stream is not the instance, so if we only care about methods invoked on the instance, we wouldn't care about these methods anyway, right?

For a moment I came to think about what if the exception refers to the `readObject()` inside the class. E.g.:
```java
public class ObjectInputStream
    extends InputStream implements ObjectInput, ObjectStreamConstants
{
    ...
    private final Object readObject(Class<?> type)
        throws IOException, ClassNotFoundException
    {
        ...
    }

    public final Object readObject()
        throws IOException, ClassNotFoundException {
        return readObject(Object.class);
    }
    ...
}
```
However I think it wouldn't make sense in this context, because these methods cannot be overridden and are also shipped with the JDK you use, so you have no way to modify them. So it probably doesn't even make sense to report errors for them, as you have no way to deal with the errors.

> Yes, you may have a scenario where calling some other object's method indirectly calls an overridable method of our instance, but I'm pretty sure you won't be able reliably detect these cases while allowing all others, so why bother going beyond the exact, simple scenario given in SER09-J?

This logic was implemented in #1716, I only extended the check and this feature was already supported.

> Coming back to my original problem, could you please, if I'm mistaken, suggest how I should rewrite the following method so spotbugs won't fail?

If I understand it correctly, this method is supposed to deserialize the object. During serialization you convert the object to a byte stream and store it on the disk. Conversely, when you deserialize, you read that exact bytestream and convert it back to the object, which shouldn't require any additional logic. 

What I see in your method is that you first created a different kind of representation of the object, which you stored on disk and now you read that different representation and try to parse it into the object. I think this transformation wasn't considered, when SER09-J was written, unless I understand something wrong.

**Comment by kohlschuetter** [comment] 2024-04-22 09:29
After reviewing [SER09-J](https://wiki.sei.cmu.edu/confluence/display/java/SER09-J.+Do+not+invoke+overridable+methods+from+the+readObject%28%29+method) and the cited [[Secure Coding Guidelines for Java SE, Version 5.0](http://www.oracle.com/technetwork/java/seccodeguide-139067.html)](http://www.oracle.com/technetwork/java/seccodeguide-139067.html), particularly:
-  Guideline 7-4 / OBJECT-4: Prevent constructors from calling methods that can be overridden

**Comment by isuckatcs** [comment] 2024-04-23 18:49
> there is no way an ObjectInputStream subclass could access `this` prematurely (other than via reflection or JNI trickery, [...])

When you use JNI, you declare the method in Java and implement it in C++ AFAIK. The C++ method has access to `this`, so can't it also fish for `curContext` inside the object pointed by `this`?

From Java, I don't see any straightforward way to get access to `this` either.

I agree that `defaultReadObject()` can indeed lead to the same problem, that this check wants to protect against, so making it an exception doesn't make sense, but for the other methods I think the error is reported correctly if the JNI or reflection tricks you refered to do work.

On the other hand, limiting the check for overridable methods invoked on `this` contradicts the cert. @JuditKnoll what is the prefere way to deal with this? Should we just limit the detection as proposed?

**Comment by gtoison** [comment] 2024-04-24 06:55
The scenario where a native library is used with a custom ObjectInputStream seems very far-fetched to me too.
The assumption is that the attacker might control the data in the input stream, but for that he doesn't really need to override methods in `ObjectInputStream`.

IMO the rule is for attacks where the code is something like:
```
if (isAdmin(in.readXyz()) {
     this.admin = true;
} else {
     ...
}
```

An attacker might get an object where the private `admin` field is set to true by overriding `isAdmin()`

**Comment by kohlschuetter** [comment] 2024-04-24 11:30
@gtoison Correct, and that (possibility 2) is why I think having this warning in the general case is important, rather than to silence it altogether. I do see some paranoid use case for the override-ObjectInputStream scenario; in case that is desired to be checked by spotbugs, such warning should then be separate, and not be enabled by default.

**Comment by kohlschuetter** [comment] 2024-06-27 19:22
Any update on this? I'm still seeing the false positive errors in 4.8.6.1

**Comment by gtoison** [comment] 2024-07-01 19:17
I've submitted PR #3029, any feedback is appreciated

**Comment by JuditKnoll** [comment] 2024-08-08 08:28
The PR fixing this issue got merged, it will be in the next release.

**Closed by JuditKnoll** 2024-08-08 08:28 UTC

**Comment by garydgregory** [comment] 2024-11-29 14:34
@gtoison 
Ty for the update!

**Comment by garydgregory** [comment] 2026-06-03 11:47
FTR, 4.9.0 doesn't work on Java 8.

**Comment by JuditKnoll** [comment] 2026-06-03 11:59
> FTR, 4.9.0 doesn't work on Java 8.

Yes, in the [4.9.0](https://github.com/spotbugs/spotbugs/releases/tag/4.9.0) release at `Changed` it's mentioned that the Java version was bumped up to 11, also in the [Readme](https://github.com/spotbugs/spotbugs#build) it's mentioned that using SpotBugs requires at least JDK 11, however it can analyze code compiled with older versions.

**Comment by garydgregory** [comment] 2026-06-03 12:21
Yep, it's all good. I was just leaving a note in the ticket for others like me who run into this issue maintaining builds on Java 8.
