### ISSUE TITLE
Findbugs on Android: java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index

### ISSUE THREAD

**Issue by a93a** [spotbugs/spotbugs#931] opened 2019-04-29 22:29 UTC
Added Findbugs plugin (via settings/plugins) to my Android project. When trying to run Findbugs to analyze project I get this error:

```
Error:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:86)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:214)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:73)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:12)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:74)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexBuilder.buildStarted(JavaBackwardReferenceIndexBuilder.java:40)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:358)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:229)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

Any ideas?

**Comment by ThrawnCA** [comment] 2019-04-30 00:12
Is that a FindBugs plugin, or SpotBugs?

**Comment by aliamid93** [comment] 2019-04-30 01:26
@ThrawnCA it is a FindBugs plugin

**Comment by TsingWei** [comment] 2019-05-23 13:33
I have the exactly the same problem on my AS 3.4.0 .

**Comment by shencang** [comment] 2019-05-23 14:57
I also encountered the same problem, android studio version is also 3.4, installed findbugs, has not been resolved

**Comment by SakuramiRin** [comment] 2019-05-27 07:33
+1 same problem AS 3.4.0

**Comment by suhailbinabdullah** [comment] 2019-05-27 09:12
+1 I also have the same problem

**Comment by yy93127** [comment] 2019-05-29 01:26
+1 same problem AS 3.4.0

**Comment by ermolnik** [comment] 2019-05-30 07:35
+1 3.4.1 AS

**Comment by ameenmaheen** [comment] 2019-06-03 10:42
+1 Same issue on Android Studio 3.4.1

**Comment by robregonm** [comment] 2019-06-14 16:34
Same error in 3.5 Beta 4

**Comment by sachin10101998** [comment] 2019-06-19 08:08
Any solution found?

**Comment by cony029** [comment] 2019-06-27 08:41
No solution ?

**Comment by y3Sai** [comment] 2019-07-02 06:32
same 3.4.1

**Comment by 603751448** [comment] 2019-07-09 02:54
相同的3.4.1

**Comment by 603751448** [comment] 2019-07-09 02:55
有没有什么解决办法呀

**Comment by Karlheinzniebuhr** [comment] 2019-07-14 21:50
I get this issue on android 3.4.2 when trying to compile an SDK from a flutter project

**Comment by whocen** [comment] 2019-07-15 17:25
Has anyone resolved this issue

**Comment by echo557** [comment] 2019-07-18 07:29
Same issue. AS3.4.1

**Comment by whocen** [comment] 2019-07-18 09:38
Hello, after I have pulled most of my hair  trying to figure this thing out because the internet seemed not to have any direct answer I went the manual route where by I check each file after another to try figure out where the problem was, see I figured it was my JDK that's the problem so I decided to test a few JDK versions from 8 to 12 and each would give me a different error after a some testing I found a similar error to this with JDK1.8.0_201 but I read a post on a russian forum that that particular error is caused by a miss configured keystore file so I generated a new keystore using a keytool from JDK12.0.1 and used the new Key to sign my app and it builds both the apk and app bundles and everything is working peachy!! In conclusion this can becaused by a number of different things it might not be solved with the same route I have taken but that's what worked for me for I figured might as well share. Happy Coding!!

**Comment by Justin-ye** [comment] 2019-08-12 08:29
+1 same problem AS 3.5

**Comment by wuyan12138** [comment] 2019-08-31 13:44
请问有解决了这个问题的吗？我也有这个问题

**Comment by CrystalRanita** [comment] 2019-09-05 01:44
Same issue in Android Studio 3.5, gradle sync and build function missing.

**Comment by lgengsy** [comment] 2019-09-05 05:16
+1 same problem AS 3.5

**Comment by moz1q1** [comment] 2019-09-11 03:19
妈蛋

**Comment by SakuramiRin** [comment] 2019-09-13 08:44
我发现了一个不完美的临时解决方法以提供给大家作为参考。
当我在使用AS Commit Changes窗口提交代码时，右边显示会有Run FindBugs analysis，勾选之后可以针对你当前修改过的文件进行正常工作的FindBugs检查！
----------------------------------------------------------------------------------------------------------
I found a temporary solution to solve this problem!
when I commit my code using the  **AS Commit Changes**, the right side of this window will show **Run FindBugs analysis**. If you checking this, you can use FindBugs normally, but only for the file whice you are changed.
Good luck for you!

**Comment by SakuramiRin** [comment] 2019-09-13 09:05
发现一个临时使用方法供大家参考。
在我提交使用AS Commit Changes窗口提交代码时候，窗口的右边显示会有一个Run FindBugs analysis勾选框，勾选之后可以针对你当前修改过的文件进行正常工作的FindBugs检查！
希望能对你们有帮助。

I found a temporary method to solve this problem and use FindBugs.
when I commit my code using the AS **Commit Changes**, the right side of this window will show **Run FindBugs analysis**. If you checking this, you can use FindBugs normally, but only for the file whice you are changed.
Hope to help you,good luck.

**Comment by zezadas** [comment] 2019-09-23 13:35
Changing java compiler to eclipse seems to work

https://blog.csdn.net/weixin_37639900/article/details/100552886

**Comment by lb7788** [comment] 2019-09-25 09:40
open the FindBugs setting, click General,then close the "Compile affected files before analyze". It works for me with Android Studio 3.5

**Comment by samtheboss** [comment] 2019-10-03 09:32
> open the FindBugs setting, click General,then close the "Compile affected files before analyze". It works for me with Android Studio 3.5

thanks man it helped

**Comment by daixu** [comment] 2019-10-16 03:10
same problem AS 3.5.1

**Comment by isurujayasighe** [comment] 2019-11-21 05:17
Thanks you @lb7788

**Comment by tanhuang01** [comment] 2019-12-16 08:38
Thank you，that work for me.

> open the FindBugs setting, click General,then close the "Compile affected files before analyze". It works for me with Android Studio 3.5

**Comment by nightcap79** [comment] 2019-12-31 19:42
To Solve this problem in Android Studio go to File-->Settings-->Build, Execution, Deployment---> Java Compiler option, change javac to eclipse, and apply.

**Comment by hazendaz** [comment] 2023-08-19 20:02
closing as users figured out issue

**Closed by hazendaz** 2023-08-19 20:02 UTC
