### ISSUE TITLE
One or more required BCEL classes were missing

### ISSUE THREAD

**Issue by DaveJarvis** [spotbugs/spotbugs#436] opened 2017-10-06 22:43 UTC
**Replicate**
On Linux:

``` .bash
cd $HOME
wget http://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/3.1.0-RC6/spotbugs-3.1.0-RC6.tgz
tar xf *gz
mv spotbugs-* spotbugs
export SPOTBUGS_HOME=$HOME/spotbugs
java -jar $SPOTBUGS_HOME/lib/spotbugs.jar
```

**Expected Results**
GUI appears.

**Actual Results**
Console shows:

> One or more required BCEL classes were missing. Ensure that bcel.jar is placed at the same directory with spotbugs.jar

**Additional Details**
``` .bash
$ find spotbugs/lib/ -type f
spotbugs/lib/jcip-annotations-1.0.jar
spotbugs/lib/asm-commons-6.0.jar
spotbugs/lib/asm-tree-6.0.jar
spotbugs/lib/jaxen-1.1.6.jar
spotbugs/lib/asm-xml-6.0.jar
spotbugs/lib/dom4j-1.6.1.jar
spotbugs/lib/jsr305-3.0.1.jar
spotbugs/lib/commons-lang-2.6.jar
spotbugs/lib/bcel-6.1.jar
spotbugs/lib/spotbugs-ant.jar
spotbugs/lib/jFormatString-3.0.0.jar
spotbugs/lib/asm-analysis-6.0.jar
spotbugs/lib/spotbugs-annotations.jar
spotbugs/lib/spotbugs.jar
spotbugs/lib/asm-6.0.jar
spotbugs/lib/asm-util-6.0.jar
spotbugs/lib/xml-apis-1.0.b2.jar
$ java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Suggestion**
Consider making a single JAR file with all dependencies listed in `META-INF/lib` or whatever path is required for the JVM to find all required libraries.

**Comment by iloveeclipse** [comment] 2017-10-07 04:37
Duplicate of #405. The fix is in HEAD.

**Closed by iloveeclipse** 2017-10-07 04:37 UTC
