### ISSUE TITLE
Spotbugs not respecting suppression

### ISSUE THREAD

**Issue by jpschewe** [spotbugs/spotbugs#920] opened 2019-04-07 00:01 UTC
When running spotbugs version 3.1.12 against this file I get an warning that the SQL prepared statement is not created from a constant string. I've added suppression and I still get the warning.

I have effort set to max and report level set to low.

```java
import static org.junit.jupiter.api.Assertions.fail;

import java.awt.EventQueue;
import java.lang.reflect.InvocationTargetException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.diffplug.common.base.Errors;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;

/**
 *
 */
public class Bug {

  @SuppressFBWarnings(value = "SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRING", justification = "Need to specify category for table name")
  public void bugMethod(final Connection testDataConn,
                        final String category,
                        final int id)
      throws SQLException, InterruptedException {
    try {
      EventQueue.invokeAndWait(Errors.rethrow().wrap(() -> {

        try (PreparedStatement prep = testDataConn.prepareStatement("SELECT * FROM "
            + category
            + " WHERE Tournament = ?")) {
          prep.setInt(1, id);

          try (final ResultSet rs = prep.executeQuery()) {
            while (rs.next()) {

              // do something
            }
          }
        }
      }));
    } catch (final InvocationTargetException e) {
      fail("Got error entering subjective scores");
    }

  }
}
```

**Comment by ThrawnCA** [comment] 2019-04-07 23:22
Which artifact are you including to get access to the SuppressFBWarnings annotation?

**Comment by jpschewe** [comment] 2019-04-07 23:58
Here are the dependencies for spotbugs/findbugs.
```
    compileOnly group: "com.github.spotbugs", name: "spotbugs-annotations", version: project.spotbugs_version
    compileOnly group: 'net.jcip', name: 'jcip-annotations', version: '1.0'
    compileOnly group: "com.google.code.findbugs", name: "jsr305", version: "3.0.1"
```

**Comment by jpschewe** [comment] 2019-04-07 23:59
Other places of this annotation are respected. If I remove the `EventQueue` call, then spotbugs respects the annotation.

**Comment by jpschewe** [comment] 2019-04-14 00:36
I added
```gradle
buildscript {
    dependencies {
        classpath group: 'net.sf.saxon', name: 'Saxon-HE', version: '9.4'
    }
}    
```

And switched back to the saxon transformer and now I get the following output
```bash
>./gradlew spotbugsMain                            
Starting a Gradle Daemon (subsequent builds will be faster)                    
                    
> Configure project :                                                 
POM relocation to an other version number is not fully supported in Gradle : xml-apis:xml-apis:2.0.2 relocated to xml-api
s:xml-apis:1.0.b2.                      
Please update your dependency to directly use the correct version 'xml-apis:xml-apis:1.0.b2'.
Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
                                                                              
> Task :spotbugsMainHtmlReport FAILED
Warning: at xsl:variable on line 348 column 56 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect
Warning: at xsl:variable on line 351 column 59 of default.xsl:                                 
  SXWN9001: A variable with no following sibling instructions has no effect
Error on line 71 of default.xsl:
  SEPM0009: Values of 'standalone' and 'omit-xml-declaration' conflict                                                                              
FAILURE: Build failed with an exception.
                                          
* Where:
Build file '/home/jpschewe/projects/fll-sw/working-dir/build.gradle' line: 396             
                                                                     
* What went wrong:                                                                             
Execution failed for task ':spotbugsMainHtmlReport'.
> net.sf.saxon.trans.XPathException: Values of 'standalone' and 'omit-xml-declaration' conflict
                                            
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with -
-scan to get full insights.                      
                                         
* Get more help at https://help.gradle.org
                             
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 2s
5 actionable tasks: 3 executed, 2 up-to-date
```

I tried adding
```gradle
   configurations.classpath {
        resolutionStrategy {
            force 'xml-apis:xml-apis:1.4.01'
        }
    }
```
to the buildscript section and the error about switching versions of the xml-apis went away, but I still got the xsl errors.

**Comment by jpschewe** [comment] 2019-04-14 00:43
@ThrawnCA Do I need to use different artifacts for my annotations?

**Comment by ThrawnCA** [comment] 2019-04-14 19:19
It's almost certainly due to the lambda function. I'm not sure whether you can annotate those.

**Comment by jerith666** [comment] 2021-07-07 13:26
#724 is the issue for suppressing warnings inside lambdas.

**Comment by gtoison** [comment] 2023-08-30 14:38
The problem is indeed that the `@SuppressFBWarnings` annotation is in the `.class` file of the parent class. When SpotBugs analyses the `.class` corresponding to the lambda, there's no annotation so the finding is reported.

I'll close this as a duplicate of #724 but unfortunately the underlying problem won't be solved anytime soon (we can't have annotations on classes corresponding to lambdas)

**Closed by gtoison** 2023-08-30 14:38 UTC

**Comment by KrnSaurabh** [comment] 2024-09-28 07:33
@gtoison Is there a way to solve this problem? I am ready to contribute provided some guidance on implementation for the same. I believe many folks have faced this issue and would be nice if SpotBugs supports this,.

**Comment by gtoison** [comment] 2024-10-09 12:17
Hello @KrnSaurabh 
You could start by writing a unit test illustrating the problem, hopefully debugging that test could help troubleshooting the issue.
We generally write test as:
- A sample class, for example: https://github.com/spotbugs/spotbugs/blob/master/spotbugsTestCases/src/java/ghIssues/Issue2837.java
- A test analysing the sample and checking the outcome, for example: https://github.com/spotbugs/spotbugs/blob/master/spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue2837Test.java
