### ISSUE TITLE
False positive for THROWS_METHOD_THROWS_CLAUSE_BASIC_EXCEPTION when calling method that declares throwing Exception

### ISSUE THREAD

**Issue by Adrodoc** [spotbugs/spotbugs#2062] opened 2022-05-23 08:33 UTC
When you have a method `a` that calls a method `b` which `throws Exception` then you too have to declare `throws Exception` on `a` unless you want to handle the exception. Spotbugs should not raise THROWS_METHOD_THROWS_CLAUSE_BASIC_EXCEPTION in such a case.

A typical example is a [Jakarta EE interceptor](https://jakarta.ee/specifications/platform/8/apidocs/javax/interceptor/invocationcontext) calling `proceed` on its `InvocationContext`:
```
package de.sanacorp.zwe.server.base.async;

import javax.interceptor.AroundInvoke;
import javax.interceptor.Interceptor;
import javax.interceptor.InvocationContext;

@Interceptor
public class SomeInterceptor {
  @AroundInvoke
  public Object aroundInvoke(InvocationContext ctx) throws Exception {
    // Do some stuff
    Object result = ctx.proceed();
    // Do some more stuff
    return result;
  }
}
```
Spotbugs raises the following warning for this simple interceptor:
```
Bug type THROWS_METHOD_THROWS_CLAUSE_BASIC_EXCEPTION
In class de.sanacorp.zwe.server.base.async.SomeInterceptor
In method de.sanacorp.zwe.server.base.async.SomeInterceptor.aroundInvoke(InvocationContext)
At SomeInterceptor.java:[lines 12-14]
```

**Comment by iloveeclipse** [comment] 2022-05-23 08:39
Duplicate of #2040

**Closed by iloveeclipse** 2022-05-23 08:39 UTC

**Comment by Adrodoc** [comment] 2022-05-23 08:42
> Duplicate of #2040

That is a different bug type though.

**Comment by iloveeclipse** [comment] 2022-05-23 09:45
> > Duplicate of #2040
> 
> That is a different bug type though.

But same "bad" detector that introduced all this false positives in https://github.com/spotbugs/spotbugs/pull/1956.
