### ISSUE TITLE
ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by virgium03** [spotbugs/spotbugs#3139] opened 2024-10-02 07:53 UTC
IntelliJ IDEA 2024.2.3 and some previous versions report this exception for SpotBugs version 1.2.8:

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.jetbrains.plugins.spotbugs.actions.AnalyzeSelectedFiles' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.jetbrains.plugins.spotbugs]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

The error is not blocking, it just appears quite frequently, when right clicking on a file iirc.

**Comment by JuditKnoll** [comment] 2024-10-02 08:14
This is the issue of the [spotbugs-intellij-plugin](https://github.com/JetBrains/spotbugs-intellij-plugin), please open your issue there. This seems to be the duplicate of https://github.com/JetBrains/spotbugs-intellij-plugin/issues/1627. It looks like there is already a PR fixing it (https://github.com/JetBrains/spotbugs-intellij-plugin/pull/1631).

**Closed by JuditKnoll** 2024-10-02 08:14 UTC
