### ISSUE TITLE
VA_FORMAT_STRING_MISSING_ARGUMENT bug won't find by spotbugs, but findbugs can find. #432

### ISSUE THREAD

**Issue by chanjetsdp** [spotbugs/spotbugs#2049] opened 2022-05-13 01:45 UTC
### **1. Generate Demo project and code**
```
mvn archetype:generate -DgroupId=ToolsQA -DartifactId=DemoMavenProject -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
```

**src/main/java/ToolsQA/App.java**

```

package ToolsQA;

/**
 * Hello world!
 *
 */
public class App 
{
    private static final String TWO_ARGS_STRING_FORMAT = "TWO:%s:%s";
    public static void main( String[] args )
    {
        System.out.println( String.format(TWO_ARGS_STRING_FORMAT,"Hello World!") );
    }
}

```
**maven project configuration**
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ToolsQA</groupId>
  <artifactId>DemoMavenProject</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>DemoMavenProject</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

<build>
<plugins>
<plugin>
  <groupId>com.github.spotbugs</groupId>
  <artifactId>spotbugs-maven-plugin</artifactId>
  <version>4.6.0.0</version>
  <dependencies>
    <!-- overwrite dependency on spotbugs if you want to specify the version of spotbugs -->
    <dependency>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs</artifactId>
      <version>4.7.0</version>
    </dependency>
  </dependencies>
</plugin>
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>findbugs-maven-plugin</artifactId>
    <version>3.0.4</version>
    <configuration>
    <maxRank>15</maxRank>
    <effort>Default</effort>
    <threshold>medium</threshold>
    <failOnError>true</failOnError>
    </configuration>
    <executions>
    <execution>
        <goals>
        <goal>check</goal>
        </goals>
        <phase>validate</phase>
    </execution>
    </executions>
</plugin>
</plugins>
</build>

</project>
```

### 2. Compile

```
mvn clean compile -DskipTests
```

### 3. RUN findbugs:  

```
mvn -B org.codehaus.mojo:findbugs-maven-plugin:3.0.4:check -Dfindbugs.maxRank=15 -Dfindbugs.effort=Default -Dfindbugs.threshold=medium -Dfindbugs.failOnError=true 

```

**RUN findbugs output** 
_**find bug: VA_FORMAT_STRING_MISSING_ARGUMENT**_
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< ToolsQA:DemoMavenProject >----------------------
[INFO] Building DemoMavenProject 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> findbugs-maven-plugin:3.0.4:check (default-cli) > :findbugs @ DemoMavenProject >>>
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.4:findbugs (findbugs) @ DemoMavenProject ---
[INFO] Fork Value is true
     [java] Warnings generated: 1
[INFO] Done FindBugs Analysis....
[INFO] 
[INFO] <<< findbugs-maven-plugin:3.0.4:check (default-cli) < :findbugs @ DemoMavenProject <<<
[INFO] 
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.4:check (default-cli) @ DemoMavenProject ---
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[INFO] Format string "%s" needs argument 2 but only 1 are provided in ToolsQA.App.main(String[]) [ToolsQA.App] At App.java:[line 12] VA_FORMAT_STRING_MISSING_ARGUMENT
[INFO] 


To see bug detail using the Findbugs GUI, use the following command "mvn findbugs:gui"



[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.491 s
[INFO] Finished at: 2022-05-13T10:24:25+08:00
[INFO] ------------------------------------------------------------------------
```

### 4. RUN spotbugs

```
mvn -B com.github.spotbugs:spotbugs-maven-plugin:4.6.0.0:check -Dspotbugs.maxRank=15 -Dspotbugs.effort=Default -Dspotbugs.threshold=medium -Dspotbugs.failOnError=true
```
**RUN spotbugs output**
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< ToolsQA:DemoMavenProject >----------------------
[INFO] Building DemoMavenProject 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> spotbugs-maven-plugin:4.6.0.0:check (default-cli) > :spotbugs @ DemoMavenProject >>>
[INFO] 
[INFO] --- spotbugs-maven-plugin:4.6.0.0:spotbugs (spotbugs) @ DemoMavenProject ---
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....
[INFO] 
[INFO] <<< spotbugs-maven-plugin:4.6.0.0:check (default-cli) < :spotbugs @ DemoMavenProject <<<
[INFO] 
[INFO] 
[INFO] --- spotbugs-maven-plugin:4.6.0.0:check (default-cli) @ DemoMavenProject ---
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.889 s
[INFO] Finished at: 2022-05-13T10:23:31+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by KengoTODA** [comment] 2022-05-13 06:20
Duplicate of #1526

**Closed by KengoTODA** 2022-05-13 06:20 UTC
