### ISSUE TITLE
Gradle build failing with "Failed to run Gradle SpotBugs Worker"

### ISSUE THREAD

**Issue by plorenz** [spotbugs/spotbugs#530] opened 2018-01-12 19:39 UTC
```
* What went wrong:
Execution failed for task ':spotbugsMain'.
> Failed to run Gradle SpotBugs Worker
   > Process 'Gradle SpotBugs Worker 38' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
2 actionable tasks: 1 executed, 1 up-to-date
```

Is there anything I can do to get more information? I've tried running with --stacktrace and --debug and neither provides any useful information.

**Comment by ArkantosC** [comment] 2018-01-31 13:25
I'm facing a similar problem. For my side the problem is happening when I added a classpath with java classses in the dependencies section.

**Comment by michalkowol** [comment] 2018-02-19 17:34
I have the same problem.

**Comment by KengoTODA** [comment] 2018-02-20 02:54
maybe better to discuss at https://github.com/spotbugs/spotbugs-gradle-plugin/

and could you share some project which can reproduce this issue?

**Comment by hongqijia** [comment] 2018-02-26 18:36
I ran into this problem too.  Is there any updates on this issue?

**Comment by jeven2016** [comment] 2018-03-06 06:30
I encountered this problem too.....   need help ...........

**Comment by JewelPengin** [comment] 2018-03-13 13:45
Linking - https://github.com/spotbugs/spotbugs-gradle-plugin/issues/11

**Comment by KengoTODA** [comment] 2018-04-28 10:13
I'll close this issue, please use spotbugs/spotbugs-gradle-plugin#11 instead.

**Closed by KengoTODA** 2018-04-28 10:13 UTC
