### ISSUE TITLE
THROWS_METHOD_THROWS_CLAUSE_BASIC_EXCEPTION with generic Exception false positive

### ISSUE THREAD

**Issue by garydgregory** [spotbugs/spotbugs#2043] opened 2022-05-06 19:28 UTC
Starting with 4.7.0, a `THROWS_METHOD_THROWS_CLAUSE_BASIC_EXCEPTION` with a generic `Exception` feels like a false positive. For example, in Apache Commons Pool git master:
```
public abstract class BaseKeyedPooledObjectFactory<K, V, E extends Exception> extends BaseObject implements KeyedPooledObjectFactory<K, V, E> {
    ...
    @Override
    public void activateObject(final K key, final PooledObject<V> p) throws E {
        // The default implementation is a no-op.
    }
...
```

**Comment by iloveeclipse** [comment] 2022-05-23 08:38
Duplicate of #2040

**Closed by iloveeclipse** 2022-05-23 08:38 UTC
