### ISSUE TITLE
Excessive log noise

### ISSUE THREAD

**Issue by ctmay4** [spotbugs/spotbugs#1305] opened 2020-09-24 19:54 UTC
I mentioned this in #266 but I would like to make an issue specifically for this.  

I am using OpenJDK 11 and version 4.5 of the Gradle plugin:

```
classpath "gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.5.0"
```

and this version of Spotbugs

```
spotbugs 'com.github.spotbugs:spotbugs:4.1.2'
```

I use Spotbugs in many projects and I've only seen this for one of them.  My build logs are filled with these types of call stacks.  The Spotbugs process seems to work perfectly but there is just a TON of noise in the build logs.  Is there any way to suppress these errors?

```
[13:34:38] :	 [Step 1/1] > Task :app-lite:spotbugsMain
[13:34:38]W:	 [Step 1/1]   Error processing2 < Z, signed_byte, true, return value from java.lang.Boolean.booleanValue()Z, r3 >iand< Z, return value from com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareFieldValues(Ljava/lang/Object;Ljava/lang/Object;)Z > @ 55 in com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareTxs : (Lcom.imsweb.seerdms.shared.entity.TreatmentProcedure;Lcom.imsweb.seerdms.shared.entity.TreatmentProcedure;)Z
[13:34:38]W:	 [Step 1/1]     java.lang.IllegalArgumentException: true
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.constantToInt(OpcodeStack.java:2197)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.pushByIntMath(OpcodeStack.java:3315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:1873)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.sawOpcode(OpcodeStack.java:2898)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:878)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.visitCode(OpcodeStack.java:2884)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:131)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.computeJumpInfo(OpcodeStack.java:2928)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2857)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2840)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.getJumpInfo(OpcodeStack.java:3057)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:3028)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:64)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:131)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:397)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.lambda$null$1(FindBugs2.java:1108)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
[13:34:38]W:	 [Step 1/1]       At com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:97)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:34:38]W:	 [Step 1/1]       At java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[13:34:38]W:	 [Step 1/1]       At java.base/java.lang.Thread.run(Thread.java:834)
[13:34:38]W:	 [Step 1/1]   Error processing2 < Z, signed_byte, true, return value from java.lang.Boolean.booleanValue()Z, r3 >iand< Z, return value from com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareRegistryFieldValues(Lcom/imsweb/seerdms/shared/entity/TreatmentProcedure;Lcom/imsweb/seerdms/shared/entity/TreatmentProcedure;)Z > @ 76 in com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareTxs : (Lcom.imsweb.seerdms.shared.entity.TreatmentProcedure;Lcom.imsweb.seerdms.shared.entity.TreatmentProcedure;)Z
[13:34:38]W:	 [Step 1/1]     java.lang.IllegalArgumentException: true
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.constantToInt(OpcodeStack.java:2197)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.pushByIntMath(OpcodeStack.java:3315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:1873)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.sawOpcode(OpcodeStack.java:2898)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:878)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.visitCode(OpcodeStack.java:2884)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:131)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.computeJumpInfo(OpcodeStack.java:2928)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2857)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2840)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.getJumpInfo(OpcodeStack.java:3057)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:3028)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:64)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:131)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:397)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.lambda$null$1(FindBugs2.java:1108)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
[13:34:38]W:	 [Step 1/1]       At com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:97)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:34:38]W:	 [Step 1/1]       At java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[13:34:38]W:	 [Step 1/1]       At java.base/java.lang.Thread.run(Thread.java:834)
[13:34:38]W:	 [Step 1/1]   Error processing2 < Z, signed_byte, true, return value from java.lang.Boolean.booleanValue()Z, r6 >iand< Z, return value from com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareFieldValues(Ljava/lang/Object;Ljava/lang/Object;)Z > @ 153 in com.imsweb.seerdms.app.autobuild.AutoBuildUtils.isDuplicateFacilityAdmission : (Lcom.imsweb.seerdms.shared.entity.FacilityAdmission;Ljava.util.Set;)Z
[13:34:38]W:	 [Step 1/1]     java.lang.IllegalArgumentException: true
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.constantToInt(OpcodeStack.java:2197)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.pushByIntMath(OpcodeStack.java:3315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:1873)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.sawOpcode(OpcodeStack.java:2898)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:878)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.visitCode(OpcodeStack.java:2884)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:131)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.computeJumpInfo(OpcodeStack.java:2928)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2857)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2840)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.getJumpInfo(OpcodeStack.java:3057)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:3028)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:64)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:131)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:397)
[13:34:38]W:	 [Step 1/1]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.lambda$null$1(FindBugs2.java:1108)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
[13:34:38]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
[13:34:38]W:	 [Step 1/1]       At com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:97)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
[13:34:38]W:	 [Step 1/1]       At org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
[13:34:38]W:	 [Step 1/1]       At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:34:38]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:34:38]W:	 [Step 1/1]       At java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:34:38]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:34:38]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[13:34:38]W:	 [Step 1/1]       At java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by iloveeclipse** [comment] 2020-09-29 18:55
Duplicate of #893

**Closed by iloveeclipse** 2020-09-29 18:55 UTC
