### ISSUE TITLE
edu.umd.cs.findbugs.classfile.ResourceNotFoundException: Resource not found: java/lang/Object.class at edu.umd.cs.findbugs.classfile.impl.ClassPathImpl.lookupResource(ClassPathImpl.java:162)

### ISSUE THREAD

**Issue by Theycallmeinsane** [spotbugs/spotbugs#2204] opened 2022-10-06 11:07 UTC
Error is copied to the clipboard

**Comment by KengoTODA** [comment] 2022-10-10 00:24
Duplicate of https://github.com/spotbugs/spotbugs/issues/1255

**Closed by KengoTODA** 2022-10-10 00:24 UTC
