### ISSUE TITLE
Which version of java should I use with this project?

### ISSUE THREAD

**Issue by S3j5b0** [spotbugs/spotbugs#1730] opened 2021-09-29 16:36 UTC
Hi, I just was involved with a course that used spotbugs for an exercise.

we experienced that a lot of the students coulnt run the project, and had java code errors thrown at them,

So I was wondering which versions of java that this project is compatible with? I couldn't really find anything about dependencies on this git.

**Comment by KengoTODA** [comment] 2021-09-30 07:08
According to the [official site](https://spotbugs.github.io/) and [official manual](https://spotbugs.readthedocs.io/en/stable/introduction.html#requirements), you need Java 8 or later to run SpotBugs:

> SpotBugs requires JRE (or JDK) 1.8.0 or later to run. However, it can analyze programs compiled for any version of Java, from 1.0 to 1.9.

**Comment by soumyajitsamanta** [comment] 2021-11-12 20:04
Hi,
My project uses java 11 and findbugs on java 11 gives the bcel error. Is there going to be update to java 11 or later. There is also a file in repository on design saying that dependency on bcel was to be removed,  is that for the above problem?

**Comment by gtoison** [comment] 2023-09-06 10:57
I'll close this as (I think) the question was answered.
In case there are some errors or further questions please open a new issue explaining what the problem is

**Closed by gtoison** 2023-09-06 10:57 UTC
