### ISSUE TITLE
Scanning code via Bamboo rendors error for new UAT sonarqube 9.9.3

### ISSUE THREAD

**Issue by Bongani-coder65** [spotbugs/spotbugs#2861] opened 2024-02-09 07:46 UTC
Hi Team,

We are upgrading our SonarQube from 9.5 to 9.9.3.
We have installed the plugin called findbugs but we getting error's when running scans from Bamboo.

Kindly please advise.
 error : 
 error	07-Feb-2024 13:08:02	    edu.umd.cs.findbugs.ba.DataflowAnalysisException: Accessing TOP or BOTTOM frame!
error	07-Feb-2024 13:08:02	      At edu.umd.cs.findbugs.ba.Frame.getStackValue(Frame.java:243)
error	07-Feb-2024 13:08:02	      At edu.umd.cs.findbugs.ba.Frame.getInstance(Frame.java:283)
error	07-Feb-2024 13:08:02	      At edu.umd.cs.findbugs.ba.npe.IsNullValueAnalysis.meetInto(IsNullValueAnalysis.java:539)
error	07-Feb-2024 13:08:02	      At edu.umd.cs.findbugs.ba.npe.IsNullValueAnalysis.meetInto(IsNullValueAnalysis.java:396)
error	07-Feb-2024 13:08:02	      At edu.umd.cs.findbugs.ba.npe.IsNullValueAnalysis.meetInto(IsNullValueAnalysis.java:73)

**Comment by JuditKnoll** [comment] 2024-02-09 08:41
Can you please give a bit more info? What is the version of the FindBugs plugin inside SonarQube? Can you please share an example, which results in this error?

**Comment by JuditKnoll** [comment] 2024-03-04 11:21
Closing this, as this is a duplicate of https://github.com/spotbugs/sonar-findbugs/issues/968. It would be really helpful, if you could share an example to reproduce the issue.

**Closed by JuditKnoll** 2024-03-04 11:21 UTC
