### ISSUE TITLE
Errors under Java 11.0.1

### ISSUE THREAD

**Issue by ctmay4** [spotbugs/spotbugs#791] opened 2018-11-06 20:26 UTC
Running under Java 11.0.1 with the latest release (3.1.8) I am seeing errors for a single class in the log.  This is a large codebase and this is the only issue I am seeing.  I assume this is a bug?

```
[15:10:19]W:	 [Step 1/1] The following errors occurred during analysis:
[15:10:19]W:	 [Step 1/1]   Error processing2 < Z, signed_byte, true, return value from java.lang.Boolean.booleanValue()Z, r3 >iand< Z, return value from com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareFieldValues(Ljava/lang/Object;Ljava/lang/Object;)Z > @ 55 in com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareTxs : (Lcom.imsweb.seerdms.shared.entity.TreatmentProcedure;Lcom.imsweb.seerdms.shared.entity.TreatmentProcedure;)Z
[15:10:19]W:	 [Step 1/1]     java.lang.IllegalArgumentException: true
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.constantToInt(OpcodeStack.java:2239)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.pushByIntMath(OpcodeStack.java:3358)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:1914)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.sawOpcode(OpcodeStack.java:2940)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:882)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.visitCode(OpcodeStack.java:2926)
[15:10:19]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:132)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.computeJumpInfo(OpcodeStack.java:2970)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2900)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2883)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.getJumpInfo(OpcodeStack.java:3101)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:3072)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:64)
[15:10:19]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:132)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
[15:10:19]W:	 [Step 1/1]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
[15:10:19]W:	 [Step 1/1]       At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
[15:10:19]W:	 [Step 1/1]       At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
[15:10:19]W:	 [Step 1/1]       At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:36)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:10:19]W:	 [Step 1/1]       At java.base/java.lang.reflect.Method.invoke(Method.java:566)
[15:10:19]W:	 [Step 1/1]       At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:102)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:10:19]W:	 [Step 1/1]       At java.base/java.lang.reflect.Method.invoke(Method.java:566)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[15:10:19]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[15:10:19]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[15:10:19]W:	 [Step 1/1]       At java.base/java.lang.Thread.run(Thread.java:834)
[15:10:19]W:	 [Step 1/1]   Error processing2 < Z, signed_byte, true, return value from java.lang.Boolean.booleanValue()Z, r3 >iand< Z, return value from com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareRegistryFieldValues(Lcom/imsweb/seerdms/shared/entity/TreatmentProcedure;Lcom/imsweb/seerdms/shared/entity/TreatmentProcedure;)Z > @ 76 in com.imsweb.seerdms.app.autobuild.AutoBuildUtils.compareTxs : (Lcom.imsweb.seerdms.shared.entity.TreatmentProcedure;Lcom.imsweb.seerdms.shared.entity.TreatmentProcedure;)Z
[15:10:19]W:	 [Step 1/1]     java.lang.IllegalArgumentException: true
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.constantToInt(OpcodeStack.java:2239)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.pushByIntMath(OpcodeStack.java:3358)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:1914)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.sawOpcode(OpcodeStack.java:2940)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:882)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.visitCode(OpcodeStack.java:2926)
[15:10:19]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:132)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.computeJumpInfo(OpcodeStack.java:2970)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2900)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2883)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.getJumpInfo(OpcodeStack.java:3101)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:3072)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:64)
[15:10:19]W:	 [Step 1/1]       At org.apache.bcel.classfile.Code.accept(Code.java:132)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
[15:10:19]W:	 [Step 1/1]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
[15:10:19]W:	 [Step 1/1]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
[15:10:19]W:	 [Step 1/1]       At com.github.spotbugs.internal.spotbugs.SpotBugsRunner.run(SpotBugsRunner.java:40)
[15:10:19]W:	 [Step 1/1]       At org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
[15:10:19]W:	 [Step 1/1]       At org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:36)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:10:19]W:	 [Step 1/1]       At java.base/java.lang.reflect.Method.invoke(Method.java:566)
[15:10:19]W:	 [Step 1/1]       At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:102)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:10:19]W:	 [Step 1/1]       At java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:10:19]W:	 [Step 1/1]       At java.base/java.lang.reflect.Method.invoke(Method.java:566)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[15:10:19]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[15:10:19]W:	 [Step 1/1]       At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[15:10:19]W:	 [Step 1/1]       At org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[15:10:19]W:	 [Step 1/1]       At java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KengoTODA** [comment] 2018-11-06 23:38
Thanks for your contribution!

As described in [contributing guideline](https://github.com/spotbugs/spotbugs/blob/release-3.1/.github/CONTRIBUTING.md), please consider to share minimal, complete, and verifiable example (Java code or Java project).

**Comment by ctmay4** [comment] 2018-11-08 17:20
I'm having a difficult time extracting a simple example.  I'll see what I can do.

**Comment by zhangfeilynu** [comment] 2018-11-13 03:34
I have the same problem，the following is the version information:
SonarQube 6.7.5
Findbugs 3.8.0(Analyze Java, Scala, Closure and JSP code with SpotBugs. 3.1.6)

The following is logs:
The following errors occurred during analysis:
  Error processing2 < Z, signed_byte, true, return value from java.lang.Boolean.booleanValue()Z, r4 >iand< Z, return value from java.lang.Boolean.booleanValue()Z, isNull, r18 > @ 761 in com.xxxx.xxxx.xxxx.xxxx.xxx.xxxServiceImpl.xxxMessage : (Ljava.lang.Integer;Ljava.lang.Integer;[Ljava.lang.String;)Ljava.lang.Boolean;
    java.lang.IllegalArgumentException: true
      At edu.umd.cs.findbugs.OpcodeStack.constantToInt(OpcodeStack.java:2240)
      At edu.umd.cs.findbugs.OpcodeStack.pushByIntMath(OpcodeStack.java:3359)
      At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:1915)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.sawOpcode(OpcodeStack.java:2941)
      At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:882)
      At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.visitCode(OpcodeStack.java:2927)
      At org.apache.bcel.classfile.Code.accept(Code.java:132)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.computeJumpInfo(OpcodeStack.java:2971)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2901)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2884)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
      At edu.umd.cs.findbugs.OpcodeStack.getJumpInfo(OpcodeStack.java:3102)
      At edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:3073)
      At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:64)
      At org.apache.bcel.classfile.Code.accept(Code.java:132)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
      At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
      At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
      At java.util.concurrent.FutureTask.run(FutureTask.java:266)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      At java.lang.Thread.run(Thread.java:745)

**Comment by ctmay4** [comment] 2018-11-28 13:54
I've tried but am so far unable to reproduce this in a small sample project.  It is 100% consistent in my large project but I know that doesn't help you.  Not sure where to go from here.

**Comment by iloveeclipse** [comment] 2020-09-29 18:56
Duplicate of #893.

**Closed by iloveeclipse** 2020-09-29 18:56 UTC
Labels: Java-11, need info
