### ISSUE TITLE
there are lots of [errorr] during analysis in 4.7.0

### ISSUE THREAD

**Issue by dlt-lee** [spotbugs/spotbugs#2081] opened 2022-06-02 14:16 UTC
[log_8_2670.zip](https://github.com/spotbugs/spotbugs/files/8824691/log_8_2670.zip)
Hi
I don't know why sportbugs throw so much more [eror] during analysis, Could you give em a hand to look at it?
Thanks

**Comment by iloveeclipse** [comment] 2022-06-02 19:49
Duplicate of https://github.com/spotbugs/spotbugs/issues/2080

**Closed by iloveeclipse** 2022-06-02 19:49 UTC
