### ISSUE TITLE
Exception processing 'pushByLongMath' with opcode 109, lhs < J, 0, cbz > and rhs < J, 0, cbz >

### ISSUE THREAD

**Issue by gvasquez-waypoint** [spotbugs/spotbugs#549] opened 2018-01-24 14:05 UTC
I haven't been able to see any project specific file references in the log, but I've provided the finbugs ouput at least (zipped for GitHub Compliance)
[findbugs-result.xml.zip](https://github.com/spotbugs/spotbugs/files/1660094/findbugs-result.xml.zip)

SonarQube: Version 6.7 (build 33306)
Findbugs plugin 3.6.0
What additional info/specs should I provide?

Log output
[WARNING] JSP files were found in the current (sub)project (/var/lib/jenkins/workspace/WaypointReports) but FindBugs requires their precompiled form. For more information on how to configure JSP precompilation : https://github.com/find-sec-bugs/find-sec-bugs/wiki/JSP-precompilation
[INFO] Loading findbugs plugin: /var/lib/jenkins/workspace/WaypointReports/target/sonar/findbugs/findsecbugs-plugin.jar
[INFO] Findbugs output report: /var/lib/jenkins/workspace/WaypointReports/target/sonar/findbugs-result.xml
The following errors occurred during analysis:
  Exception processing 'pushByLongMath' with opcode 109, lhs < J, 0, cbz > and rhs < J, 0, cbz >
    java.lang.ArithmeticException: / by zero
      At edu.umd.cs.findbugs.OpcodeStack.pushByLongMath(OpcodeStack.java:3420)
      At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:1943)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.sawOpcode(OpcodeStack.java:2906)
      At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:882)
      At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.visitCode(OpcodeStack.java:2892)
      At org.apache.bcel.classfile.Code.accept(Code.java:132)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.computeJumpInfo(OpcodeStack.java:2936)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2866)
      At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2849)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
      At edu.umd.cs.findbugs.OpcodeStack.getJumpInfo(OpcodeStack.java:3067)
      At edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:3038)
      At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:64)
      At org.apache.bcel.classfile.Code.accept(Code.java:132)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
      At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
      At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1083)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:280)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:226)
      At java.util.concurrent.FutureTask.run(FutureTask.java:266)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At java.lang.Thread.run(Thread.java:748)

**Comment by iloveeclipse** [comment] 2018-01-28 08:13
This is a duplicate of #413. Please update to SpotBugs 3.1.0.

**Closed by iloveeclipse** 2018-01-28 08:13 UTC

**Comment by gvasquez-waypoint** [comment] 2018-01-29 12:05
Thanks, but there seems to be some confusion on SonarQube side as the GUI reports 3.6.0 installed, but with a 3.6.1 "footnote" and, doesn't offer upgrading to 3.6.1 yet. I guess I'll just have to wait until the proper plug-in has been release to upgrade to 3.6.1 (See attached image
![captura de pantalla 2018-01-29 a las 9 03 34 a m](https://user-images.githubusercontent.com/14003078/35509607-8fcbd67a-04d3-11e8-88fa-850d2dc50ae6.png)
)

**Comment by gvasquez-waypoint** [comment] 2018-01-29 12:06
Oops, I took mixed numbers, I currently have plugin 3.6.0 way ahead of 3.1.0

**Comment by wilx** [comment] 2018-03-16 08:08
I am seeing something similar here with Findbugs 3.6.0 installed:

```
06:45:35 The following errors occurred during analysis:
06:46:05   Exception processing 'pushByLongMath' with opcode 109, lhs < J, 0, r6, cbz > and rhs < J, 0, r8, cbz >
06:46:05     java.lang.ArithmeticException
```

The exception does not seem to say what was exactly the error and there is no call stack either.
