### ISSUE TITLE
missing bug code for keySECEMA

### ISSUE THREAD

**Issue by SpatialJ** [spotbugs/spotbugs#1028] opened 2019-10-24 06:43 UTC
I get this error using the maven plugin:

`  [java] Exception in thread "main" java.lang.IllegalArgumentException: Error: missing bug code for keySECEMA
     [java]     at edu.umd.cs.findbugs.DetectorFactoryCollection.getBugCode(DetectorFactoryCollection.java:509)
     [java]     at edu.umd.cs.findbugs.SortedBugCollection.writeBugCodes(SortedBugCollection.java:663)
     [java]     at edu.umd.cs.findbugs.SortedBugCollection.writeEpilogue(SortedBugCollection.java:569)
     [java]     at edu.umd.cs.findbugs.SortedBugCollection.writeXML(SortedBugCollection.java:548)
     [java]     at edu.umd.cs.findbugs.SortedBugCollection.writeXML(SortedBugCollection.java:457)
     [java]     at edu.umd.cs.findbugs.XMLBugReporter.finish(XMLBugReporter.java:47)
     [java]     at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java]     at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java]     at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java]     at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java]     at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1165)
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)`

im using this version:
` <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <version>3.1.12.2</version>
                <dependencies>
                  
                  <dependency>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs</artifactId>
                    <version>4.0.0-beta4</version>
                  </dependency>
                </dependencies>
              </plugin>`

**Comment by carstenartur** [comment] 2020-10-17 06:25
I see this since we updated the spotbugs-maven-plugin from 4.0.4 to 4.1.3
See https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-SpotBugs/

**Comment by iloveeclipse** [comment] 2020-10-17 07:56
> I see this since we updated the spotbugs-maven-plugin from 4.0.4 to 4.1.3
> See https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-SpotBugs/

I don't see there any such error. Could you please provide direct link to the build with error?

**Comment by iloveeclipse** [comment] 2020-10-17 08:03
Please also note, you are most likely use https://github.com/find-sec-bugs plugin, 

https://github.com/find-sec-bugs/find-sec-bugs/blob/246ed773aad4b1e540734a52b781a1e3f492bb52/findsecbugs-plugin/src/main/resources/metadata/messages.xml#L3977,

so if the bug code from this plugin is missing, you should open bug here: https://github.com/find-sec-bugs/find-sec-bugs/issues

**Comment by carstenartur** [comment] 2020-10-17 08:06
see https://git.eclipse.org/r/c/platform/eclipse.platform.releng.aggregator/+/170734

**Comment by iloveeclipse** [comment] 2020-10-17 08:13
> see https://git.eclipse.org/r/c/platform/eclipse.platform.releng.aggregator/+/170734

That is a different issue  #1272, fixed via #1326 in 4.1.4 already.

`Exception in thread "main" java.lang.IllegalArgumentException: Error: missing bug code for keyJUA
     [java] 	at edu.umd.cs.findbugs.DetectorFactoryCollection.getBugCode(DetectorFactoryCollection.java:509)`

Please update your maven config to use new version.

**Comment by iloveeclipse** [comment] 2020-10-17 08:16
Closing this one - is not caused by spotbugs / can't be fixed by spotbugs.

**Closed by iloveeclipse** 2020-10-17 08:16 UTC

**Comment by iloveeclipse** [comment] 2020-10-17 08:17
> Bug code here is keyJUA not keySECEMA. Nevertheless its looking to be slightly fragile regarding version dependencies.

It is not version dependent, it is simply broken configuration.
