### ISSUE TITLE
False positive with Java 11

### ISSUE THREAD

**Issue by mikebell90** [spotbugs/spotbugs#878] opened 2019-02-13 22:50 UTC
Compillation Java 8 to 8 bytecode - no issues
Compilation Java 11 to 8 bytecode:

 @Override
        public void processLines(Consumer<String> processor) {
            try (Stream<String> lines = Files.lines(pathIncludingBase)) {
                lines.forEach(processor);
            } catch (IOException | UncheckedIOException e) {
                throw new ConfigurationException("Can't open " + pathIncludingBase, e);
            }
        }

gives us 
[ERROR] Nullcheck of lines at line 97 of value previously dereferenced in com.opentable.frontdoor.configuration.ConfigSourceFactoryImpl$ForLocalFile.processLines(Consumer) [com.opentable.frontdoor.configuration.ConfigSourceFactoryImpl$ForLocalFile, com.opentable.frontdoor.configuration.ConfigSourceFactoryImpl$ForLocalFile] At ConfigSourceFactoryImpl.java:[line 97]Redundant null check at ConfigSourceFactoryImpl.java:[line 98] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE

**Comment by mikebell90** [comment] 2019-02-13 22:50
3.1.11 spotbugs, 3.1.11 maven spotbugs

**Comment by aaime** [comment] 2019-03-01 09:17
Seeing the same when java 11 builds a try-with-resource on my open source project, I get a lot of of those and the lines referenced are not matching the sources, like the redundant check is pointing at the final closing parenthesis of the try-with-resource

**Comment by markkolich** [comment] 2019-03-30 05:35
I believe this is a duplicate of https://github.com/spotbugs/spotbugs/issues/259.

**Comment by mikebell90** [comment] 2019-03-30 07:59
No that one #259 was originally about a go with two try usings. This is about with java 11 one try using giving an fp

**Comment by jscancella** [comment] 2019-11-27 13:53
Here is a minimal project that reproduces the error
https://github.com/jscancella/spotBugsIssue878

**Comment by jscancella** [comment] 2020-02-02 20:59
@KengoTODA  @markkolich any idea what milestone/timeline for fixing this? I can imagine this is going to be showstopper for anyone using try with resources on java 11.

**Comment by KengoTODA** [comment] 2020-09-25 07:41
#259 has been closed by [v4.1.3](https://github.com/spotbugs/spotbugs/releases/tag/4.1.3), please have a try.

**Closed by KengoTODA** 2020-09-25 07:41 UTC
Labels: Java-11, false positive

**Comment by jscancella** [comment] 2020-10-01 17:03
@KengoTODA I tested in my personal project and after setting
```
spotbugs {
  toolVersion = '4.1.3'
}
```
it fixed the issue for me.
