### ISSUE TITLE
Use of Spotbugs with Java 21 yields "Unsupported class file major version 65"

### ISSUE THREAD

**Issue by jbennett2091** [spotbugs/spotbugs#2567] opened 2023-09-20 07:03 UTC
I have a project that has been compiling successfully using Java 17.0.7 and Spotbugs 4.7.3 via Gradle.  When I upgrade to jdk-21, the build starts to fail as it appears that spotbugs does not understand the JDK-21 created .CLASS files.

Is there a version of spotbugs that supports Java 21?

Stacktrace:
> Task :spotbugsTest
Build cache key for task ':spotbugsTest' is 8d564c061a5ca34bbb39c18f74fa2141
Task ':spotbugsTest' is not up-to-date because:
  Task has failed previously.
Running SpotBugs by Gradle no-isolated Worker...
Starting process 'command 'C:\Program Files\Java\jdk-21\bin\java.exe''. Working directory: C:\Users\4556914\git\eai-3539462-humodifier Command: C:\Program Files\Java\jdk-21\bin\java.exe -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\gradle-8.1\caches\modules-2\files-2.1\org.slf4j\slf4j-simple\2.0.0\bf7158cef919bb65a6de45766fcf0546a88f5907\slf4j-simple-2.0.0.jar;C:\Users\4556914\.m2\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;C:\gradle-8.1\caches\modules-2\files-2.1\com.github.spotbugs\spotbugs\4.7.3\71b7e768bff5b99695874f9e5c34197f871d60fb\spotbugs-4.7.3.jar;C:\gradle-8.1\caches\modules-2\files-2.1\com.github.spotbugs\spotbugs-annotations\4.7.3\46fb4f0ae2e69eafa963711cc5c3369ac81aa31f\spotbugs-annotations-4.7.3.jar;C:\gradle-8.1\caches\modules-2\files-2.1\jaxen\jaxen\1.2.0\c10535a925bd35129a4329bc75065cc6b5293f2c\jaxen-1.2.0.jar;C:\gradle-8.1\caches\modules-2\files-2.1\net.sf.saxon\Saxon-HE\11.4\d926a13f2717ad1ea6e051550b8fd6207a587051\Saxon-HE-11.4.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.17.2\fa43ba4467f5300b16d1e0742934149bfc5ac564\log4j-core-2.17.2.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.ow2.asm\asm-commons\9.4\8fc2810ddbcbbec0a8bbccb3f8eda58321839912\asm-commons-9.4.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.ow2.asm\asm-util\9.4\ab1e0a84b72561dbaf1ee260321e72148ebf4b19\asm-util-9.4.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\9.4\a5fec9dfc039448d4fd098fbaffcaf55373b223\asm-analysis-9.4.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.ow2.asm\asm-tree\9.4\a99175a17d7fdc18cbcbd0e8ea6a5d276844190a\asm-tree-9.4.jar;C:\Users\4556914\.m2\repository\org\ow2\asm\asm\9.4\asm-9.4.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.apache.bcel\bcel\6.5.0\79b1975ec0c7a6c1a15e19fb3a58cc4041b4aaea\bcel-6.5.0.jar;C:\Users\4556914\.m2\repository\net\jcip\jcip-annotations\1.0\jcip-annotations-1.0.jar;C:\Users\4556914\.m2\repository\org\dom4j\dom4j\2.1.3\dom4j-2.1.3.jar;C:\Users\4556914\.m2\repository\org\apache\commons\commons-text\1.10.0\commons-text-1.10.0.jar;C:\Users\4556914\.m2\repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.xmlresolver\xmlresolver\4.4.3\aa8421211b0f69b5572d2d4b4252b2d87f957754\xmlresolver-4.4.3.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.xmlresolver\xmlresolver\4.4.3\89079ec236d9683bb5f6f5cf4bef0cfc01b46e55\xmlresolver-4.4.3-data.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.apache.httpcomponents.client5\httpclient5\5.1.4\208f9eed6d6ab709e2ae7a75b457ef60c0baefa5\httpclient5-5.1.4.jar;C:\Users\4556914\.m2\repository\com\google\code\gson\gson\2.9.1\gson-2.9.1.jar;C:\Users\4556914\.m2\repository\org\apache\logging\log4j\log4j-api\2.17.2\log4j-api-2.17.2.jar;C:\Users\4556914\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.apache.httpcomponents.core5\httpcore5-h2\5.1.5\624660339afd5006d427457e6b10b10b32fd86f1\httpcore5-h2-5.1.5.jar;C:\gradle-8.1\caches\modules-2\files-2.1\org.apache.httpcomponents.core5\httpcore5\5.1.5\df9da3a1fa2351c4790245400ed28d78a8ddd3fc\httpcore5-5.1.5.jar;C:\gradle-8.1\caches\modules-2\files-2.1\xml-apis\xml-apis\1.4.01\3789d9fada2d3d458c4ba2de349d48780f381ee3\xml-apis-1.4.01.jar;C:\Users\4556914\.m2\repository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar edu.umd.cs.findbugs.FindBugs2 -exitcode -pluginList C:\gradle-8.1\caches\modules-2\files-2.1\com.h3xstream.findsecbugs\findsecbugs-plugin\1.12.0\13ea511cee9ba3d683d87404c591897dd7fee67\findsecbugs-plugin-1.12.0.jar -timestampNow -auxclasspathFromFile C:\Users\4556914\git\eai-3539462-humodifier\build\spotbugs\auxclasspath\spotbugsTest -sourcepath C:\Users\4556914\git\eai-3539462-humodifier\src\test\resources;C:\Users\4556914\git\eai-3539462-humodifier\src\test\java -include C:\Users\4556914\git\eai-3539462-humodifier\config\spotbugs\spotbugs-include.xml -exclude C:\Users\4556914\git\eai-3539462-humodifier\config\spotbugs\spotbugs-exclude.xml -projectName eai-3539462-humodifier (spotbugsTest) -release 1.0.7 -analyzeFromFile C:\Users\4556914\git\eai-3539462-humodifier\build\spotbugsTest-analyse-class-file.txt
Successfully started process 'command 'C:\Program Files\Java\jdk-21\bin\java.exe''
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
The following errors occurred during analysis:
  Error scanning java/lang/Object for referenced classes
    java.lang.IllegalArgumentException: Unsupported class file major version 65
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
      At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
      At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
      At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
  Unable to get XClass for java/lang/IllegalAccessException
    java.lang.IllegalArgumentException: Unsupported class file major version 65
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
      At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:693)
      At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
      At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:909)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:252)
      At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
      At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)

**Comment by hazendaz** [comment] 2023-09-22 01:42
we will be working to get a release as soon as possible.  currently our CI runs on jdk 17, we need to confirm it works with jdk 21 still.

**Comment by xzel23** [comment] 2023-09-24 14:17
It looks like (at least?) org.objectweb.asm has to be updated. After some searcing around I found that it's declared in `gradle/libs/versions`, the last place I looked. It's actually one of the ways described in the gradle docs, so I should rather blame the gradle authors.
However, the version is already at 9.5, the latest release that should already support Java 21. This change was made on march 27 this year. The latest Spotbugs version 4.7.3 was released in october last year. I think it might be worthwhile to release a beta version that will either already work with Java 21, or show other issues that have to be tackled - exactly what a beta is for.
What are the SpotBugs developers thoughts about this?

**Comment by hazendaz** [comment] 2023-09-25 00:38
@xzel23 any user can override the dependencies at any time to be compatible.  In fact, spotbugs maven plugin using 4.7.3 is fully compatible for a while.

**Comment by xzel23** [comment] 2023-09-25 04:00
@hazendaz ehm, sorry I thik I still don't get it. Spotbugs maven plugin is fully compatible with what? Spotbugs 4.7.3? The problem is that spotbugs 4.7.3 is not compatible with Java 21. It might run with Java 21, but it cannot process Java 21 class files.

Anyway, here's the workaround for gradle users (something similar should be possible with Maven in the dependencyManagement section, but I don't have a Maven project lying around):

- in your build.gradle.kts (look up the syntax if you are using groovy DSL) add the following lines to pull in the new asm version:

```
    configurations.all {
        resolutionStrategy {
            force("org.ow2.asm:asm:9.5")
            force("org.ow2.asm:asm-analysis:9.5")
            force("org.ow2.asm:asm-commons:9.5")
            force("org.ow2.asm:asm-tree:9.5")
            force("org.ow2.asm:asm-util:9.5")
        }
    }

```

At least that does the trick for me. However I still think it would be a good idea to release a beta version of spotbugs that is compiled with the new asm version.

**Comment by ijuma** [comment] 2023-09-25 13:06
The workaround affects runtime dependencies too, it is indeed preferable for spotbugs to release a new version after bumping the asm version to 9.5.

**Comment by hazendaz** [comment] 2023-09-25 13:10
maven plugin is compatible with jdk 21 now.  Has been for months.  We haven't released spotbugs yet as running into a few issues plus main releasers are not available now.  We are working on that.  My point was you can override and continue without issue.

**Comment by hazendaz** [comment] 2023-09-25 13:11
note: maven users need to do nothing, its already default overriding all spotbugs.  We probably should do same on gradle plugin.

**Comment by rpalcolea** [comment] 2023-09-25 16:57
For Gradle, you probably want something like 

```
configurations.named('spotbugs').configure {
  resolutionStrategy.eachDependency { DependencyResolveDetails details ->
       if (details.requested.group == 'org.ow2.asm') {
            details.useVersion '9.5'
            details.because "Asm 9.5 is required for JDK 21 support"
      }
  }
}
```

This will move you to 9.5 in all modules while also doing it only for the `spotbugs` configuration so only affects spotbugs tooling and not all the classpaths

**Comment by juergenzimmermann** [comment] 2023-09-25 19:00
Here is the code adapted for Kotlin DSL:

```
configurations.named("spotbugs").configure {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.ow2.asm") {
            useVersion("9.5")
            because("Asm 9.5 is required for JDK 21 support")
        }
    }
}
```

**Comment by hazendaz** [comment] 2023-09-30 20:50
closing as work arounds exist and we will be releasing shortly.

**Closed by hazendaz** 2023-09-30 20:50 UTC

**Comment by seyfahni** [comment] 2023-10-09 14:11
For maven the workaround looks like this:
```xml
<plugin>
    <groupId>com.github.spotbugs</groupId>
    <artifactId>spotbugs-maven-plugin</artifactId>
    <version>4.7.3.0</version>
    <dependencies>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>9.5</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-analysis</artifactId>
            <version>9.5</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-commons</artifactId>
            <version>9.5</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-tree</artifactId>
            <version>9.5</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-util</artifactId>
            <version>9.5</version>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by hazendaz** [comment] 2023-10-10 00:19
The latest maven plugin requires no work around.  It is built in and will always be so.  Use 4.7.3.6.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by perlun** [comment] 2023-11-29 07:58
For reference, should be fixed in 4.8.0 because of the following changes:

- https://github.com/spotbugs/spotbugs/pull/2391
- https://github.com/spotbugs/spotbugs/pull/2578

@hazendaz - I submitted a PR to add this to the release notes, since I noted that it seemed to be missing there: https://github.com/spotbugs/spotbugs/pull/2724

**Comment by hazendaz** [comment] 2023-11-29 12:22
@perlun Typically we don't bother adding items renovate updates to release notes as its manual process currently. Possibly we can enhance that, this one as fine though as it more directly indicates jdk 21 and touches all these tickets.  You may also now notice we have jdk 21 as a used build on github actions as of last night as kotlin in gradle 8.5 rc's now fully support 21 as well.

**Comment by perlun** [comment] 2023-11-29 12:31
Sounds good @hazendaz, Judit already added it to the release notes. Like you say, this is such an important change that it perhaps makes sense to update the release notes despite it's a bit manual.

Sounds great that you run on both JDK 17 and 21 in CI. :+1:
