### ISSUE TITLE
Any plans to support kotlin?

### ISSUE THREAD

**Issue by AdityaAnand1** [spotbugs/spotbugs#573] opened 2018-02-27 03:21 UTC
😁

**Comment by ice1000** [comment] 2018-03-01 06:15
I tried using this to analyze my kotlin codes, no effect. Only bugs in Java codes are displayed.

**Comment by h3xstream** [comment] 2018-05-07 19:13
I have been developing in Kotlin for few projects. Looking at the bytecode, I would say that this JVM language is by far the easiest to support if compare to Scala or Groovy.

 - Add analog API to specified in detectors that need it.
 - Plugin for IDE and CI would need to implements a solid multi-language support. \*

 \* I have already started part of it for the Sonar Plugin.

**Comment by xenoterracide** [comment] 2018-12-14 01:51
detekt says it uses the kotlin parse tree, where spotbugs is bytecode analysis.

**Comment by dnsbtchr** [comment] 2021-05-06 07:57
Hey, any news in this area? We use the find-sec-bugs plugin and would love to use it for our Kotlin projects as well.

**Comment by ThrawnCA** [comment] 2021-05-06 23:19
Theoretically it is possible to run SpotBugs on any Java bytecode. In practice, Kotlin probably generates patterns that SpotBugs doesn't like, but you could probably just write exclusion rules for them.

**Comment by dnsbtchr** [comment] 2021-05-07 05:43
So I just ran SpotBugs with it's Maven plugin on a project which contains Java and Kotlin. I added Java class with a know bug pattern from the findsecbugs plugin to the project and SpotBugs complained about it (as I expected it to). Then I converted the same class to Kotlin and it didn't complain. Is that the expected behaviour? From your answer I'd rather expect it to complain maybe about other weird things on top of the actual issue or did I get that wrong? 🤔

**Comment by ThrawnCA** [comment] 2021-05-07 08:10
Depends on exactly what byte code it generated. Maybe Kotlin avoids whatever the bug was?

**Comment by dnsbtchr** [comment] 2021-05-07 08:16
I doubt it because I used this code and I don't know what Kotlin could do to prevent the issue.
`String generateSecretToken() {
    Random r = new Random();
    return Long.toHexString(r.nextLong());
}`
It's from https://find-sec-bugs.github.io/bugs.htm#PREDICTABLE_RANDOM

**Comment by gtoison** [comment] 2022-06-19 12:00
If anyone is interested I've got a pull request to use SpotBugs to analyze Kotlin in the SonarQube plugin; https://github.com/spotbugs/sonar-findbugs/pull/569
I've tested by analyzing the https://github.com/detekt/detekt and https://github.com/jitsi/jitsi-videobridge projects and the issues detected seem to make sense for the most part.
I don't know Kotlin so it would be appreciated if anyone could try this out and give feedback, please let me know if you're interested.

The tricky part is that due to the Kotlin compilation process, the bytecode in a .class file might be from different source files, so I needed to analyse the [SMAP](https://jakarta.ee/specifications/debugging/2.0/jdsol-spec-2.0.html) section to find which line comes from which source file (and the corresponding line).
In particular SpotBugs detects a lot of issues in bytecode that is actually from the Kotlin arrays and collections built-in classes.

**Comment by tianyu** [comment] 2023-09-11 22:43
For what it's worth, I tried it out and spotbugs seems to work: https://github.com/tianyu/spotbugs-with-kotlin

**Comment by gtoison** [comment] 2023-09-12 16:40
Thanks for the feedback!
Unless someone thinks otherwise I suppose that we can close this issue.

**Closed** 2023-09-12 22:37 UTC
