### ISSUE TITLE
Spotbugs IDEA plugin was compiled with target version 55 (Java 11)

### ISSUE THREAD

**Issue by diskostu** [spotbugs/spotbugs#1110] opened 2020-03-27 21:36 UTC
As stated in #515 , the plugin was released, and I tried it out immediately.

```java
Caused by: java.lang.UnsupportedClassVersionError: org/jetbrains/plugins/spotbugs/gui/settings/SearchableOptionContributorImpl has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Well, we still use JDK 8 in our company (I know, I know...).
So I cannot use the plugin in IntelliJ.
Would it be possible to compile it with target version 52 (Java 8)?

**Comment by amaembo** [comment] 2020-03-29 08:03
As stated in #515:

> Please report all the issues to the plugin tracker
> https://github.com/JetBrains/spotbugs-intellij-plugin/issues

Also, IntelliJ IDEA has its own runtime bundled. Now it's based on Java 11. It's highly recommended to use it to start IDEA itself. It has nothing to do with your projects. You can still develop even Java 6 project using IntelliJ IDEA, which runs on Java 11 runtime. It's very likely that IDEA 2020.2 will refuse to start on Java 8 completely and you will have to migrate anyway. Also, bundled runtime (JBR) has tons of fixes (in particular, in font rendering, HiDPI support, emoji support, etc, etc) absent in other distributions, so again you should have very strong reasons to not use it.

**Comment by hazendaz** [comment] 2023-07-18 01:47
closing as not our issue.  The issue is with intellij.  Assume since figured out but if not open ticket with intellij against their plugin.  Its super important to open at right place or tickets just sit in the dust bin.

**Closed by hazendaz** 2023-07-18 01:47 UTC
