### ISSUE TITLE
Java 14 instanceof pattern matching causes false positive SA_LOCAL_SELF_COMPARISON

### ISSUE THREAD

**Issue by ewirch** [spotbugs/spotbugs#1275] opened 2020-09-02 15:19 UTC
Running spot bugs on this code:
```
if (!(server.getThreadPool() instanceof ThreadPool.SizedThreadPool sizedThreadPool)) throw new IllegalStateException("Expecting Jetty to use a SizedThreadPool.");
```
results in
```
<BugPattern type="SA_LOCAL_SELF_COMPARISON" abbrev="SA" category="CORRECTNESS">
  <ShortDescription>Self comparison of value with itself</ShortDescription>
  <Details>
    <![CDATA[ <p> This method compares a local variable with itself, and may indicate a typo or a logic error. Make sure that you are comparing the right things. </p> ]]>
  </Details>
</BugPattern>
```
There is obviously no self comparison in the source code.

To reproduce: extract attached project, run:
```
./gradlew spotbugsMain
```
[test-project.zip](https://github.com/spotbugs/spotbugs/files/5163192/test-project.zip)

**Comment by KengoTODA** [comment] 2020-09-03 11:51
Duplicate of #1136

**Closed** 2021-04-09 10:18 UTC
Labels: Java-14
